starkware-libs/papyrus

crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/transaction.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1412)

feat(JSON-RPC): new method get_transaction_status

---

crates/papyrus_execution/src/execution_utils.rs
crates/papyrus_execution/src/state_reader.rs
crates/papyrus_execution/src/state_reader_test.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1420)

feat(execution): pending support for ExecutionStateReader::get_nonce

---

crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/transaction.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1423)

feat(JSON-RPC): add ExecutionResources to transaction receipt

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1424)

fix(execution): use the right values to check if the node is synced

---

crates/papyrus_execution/src/state_reader.rs
crates/papyrus_execution/src/state_reader_test.rs

- refactor(starknet_client): move small structs of StateDiff to common (#1381)
- feat(execution): add pending members to ExecutionStateReader (#1386)
- feat(execution): pending support for ExecutionStateReader::get_storage_at (#1407)
- feat(execution): pending support for ExecutionStateReader::get_class_hash_at (#1410)
- feat(execution): pending support for ExecutionStateReader::get_compiled_class_hash_at (#1414)
- feat(execution): pending support for ExecutionStateReader::get_compiled_contract_class (#1418)
- feat(execution): pending support for ExecutionStateReader::get_nonce (#1420)
- fix(execution): get_compiled_contract_class looks for pending deprecated classes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

fix(execution): get_compiled_contract_class looks for pending deprecated classes

---

crates/papyrus_execution/src/lib.rs

- chore(JSON-RPC): update 0.5 RPC spec only with already implemented ch… (#1408)
- chore(JSON-RPC): update 0.5 RPC spec only with already implemented ch… (#1409)
- feat(starknet_client): client's Block supports v0.13 blocks (#1415)
- fix(sync): pending sync handles the block_hash field correctly (#1402)
- feat(JSON-RPC): new method spec_version (#1411)
- test(storage): add regression test for cairo hints encoding (#1393)
- chore(JSON-RPC): delete pendingTransactions from spec (#1417)
- feat(JSON-RPC): add l1_gas_price and starknet_version to block header (#1416)
- feat(JSON-RPC): add type to transaction trace (#1419)
- feat(JSON-RPC): new method get_transaction_status (#1412)
- fix(execution): verify_contract_exists looks at pending as well and fix call to verify_node_synced
- - -
This …

fix(execution): verify_contract_exists looks at pending as well

---

crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_5/api/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1422)

chore(JSON-RPC): merge v0_4 into v0_5

---

crates/papyrus_rpc/src/lib.rs
crates/papyrus_rpc/src/state.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1427)

feat(JSON-RPC): add support for pending to call

---

Cargo.lock
config/default_config.json
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_monitoring_gateway/src/gateway_test.rs
crates/papyrus_monitoring_gateway/src/lib.rs
crates/papyrus_node/src/bin/dump_config.rs
crates/starknet_client/src/reader/mod.rs
crates/starknet_client/src/writer/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1308)

feat(monitoring): add is_ready function to the monitoring gateway

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_execution/src/state_reader.rs
crates/papyrus_execution/src/state_reader_test.rs
crates/papyrus_execution/src/test_utils.rs
crates/papyrus_rpc/src/state.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1430)

fix(execution): get timestamp, gas price, sequencer from pending block if present

---

crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs

- fix(execution): get timestamp, gas price, sequencer from pending block if present
- feat(JSON-RPC): add support for pending to simulate_transactions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1432)

feat(JSON-RPC): add support for pending to simulate_transactions

---

crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs

- fix(execution): get timestamp and gas price from pending block if present
- feat(JSON-RPC): add support for pending to estimate_fee
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1431)

feat(JSON-RPC): add support for pending to estimate_fee

---

crates/papyrus_common/src/pending_classes.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1439)

perf(common): improve PendingClasses::clone by storing the classes in an Arc

---

crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs
crates/starknet_client/src/writer/starknet_gateway_client_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1435)

test(monitoring): test is_alive of the gateway and the feeder gateway

---

crates/papyrus_rpc/src/lib.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_storage/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1440)

fix(JSON-RPC): fail rpc requests to read block content in StateOnly mode

---

crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1444)

feat(JSON-RPC): add support for pending to trace_block_transactions

---

crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs

- feat(JSON-RPC): add support for pending to trace_block_transactions
- feat(JSON-RPC): add support for pending to trace_transaction
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1446)

feat(JSON-RPC): add support for pending to trace_transaction

---

crates/papyrus_execution/src/objects.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1449)

fix(execution): use the correct field for from_address

---

Cargo.lock
crates/papyrus_rpc/Cargo.toml
crates/papyrus_rpc/resources/l1handler_tx.json
crates/papyrus_rpc/src/v0_5/transaction.rs
crates/papyrus_rpc/src/v0_5/transaction_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1442)

feat(JSON-RPC): calculate l1->l2 message hash for L1Handler transactions

---

crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/transaction.rs
crates/papyrus_rpc/src/v0_5/transaction_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1443)

feat(JSON-RPC): add msg hash to L1Handler receipt

---

crates/papyrus_sync/src/sources/central.rs
crates/papyrus_sync/src/sources/central_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1453)

perf(sync): add casm cache

---

crates/papyrus_rpc/src/v0_4/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1454)

fix(JSON-RPC): convert v3 transactions without error

---

crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/block.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1450)

refactor(JSON-RPC): get_block_number returns latest block on Pending

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1457)

chore: publish 0.2.0-rc3

---

crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1460)

fix(JSON-RPC): fix txn receipt schema

---

crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/block.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_5/transaction.rs

- chore(JSON-RPC): merge rpc v0_4 into v0_5 with conflicts
- chore(JSON-RPC): fix conflicts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1459)

chore(JSON-RPC): merge rpc v0_4 into v0_5

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/error.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_5/write_api_error.rs
crates/papyrus_rpc/src/v0_5/write_api_error_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1456)

feat(execution, JSON-RPC): error handling in execution

---

crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_6/starknet_trace_api_openrpc.json
crates/papyrus_rpc/resources/V0_6/starknet_write_api.json
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/block.rs
crates/papyrus_rpc/src/v0_6/broadcasted_transaction.rs
crates/papyrus_rpc/src/v0_6/broadcasted_transaction_test.rs
crates/papyrus_rpc/src/v0_6/deprecated_contract_class.rs
crates/papyrus_rpc/src/v0_6/error.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_6/mod.rs
crates/papyrus_rpc/src/v0_6/snapshots/papyrus_rpc__v0_5__write_api_error__write_api_error_test__starknet_error_to_declare_error_snapshot.snap
crates/papyrus_rpc/src/v0_6/snapshots/papyrus_rpc__v0_5__write_api_error__write_api_error_test__starknet_error_to_deploy_account_error_snapshot.snap
crates/papyrus_rpc/src/v0_6/snapshots/papyrus_rpc__v0_5__write_api_error__write_api_error_test__starknet_error_to_invoke_error_snapshot.snap
crates/papyrus_rpc/src/v0_6/state.rs
crates/papyrus_rpc/src/v0_6/transaction.rs
crates/papyrus_rpc/src/v0_6/transaction_test.rs
crates/papyrus_rpc/src/v0_6/write_api_error.rs
crates/papyrus_rpc/src/v0_6/write_api_error_test.rs
crates/papyrus_rpc/src/v0_6/write_api_result.rs
crates/papyrus_rpc/src/v0_6/write_api_result_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1461)

chore(JSON-RPC): copy rpc 0.5 to 0.6

---

crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_6/starknet_trace_api_openrpc.json
crates/papyrus_rpc/resources/V0_6/starknet_write_api.json
crates/papyrus_rpc/src/api.rs
crates/papyrus_rpc/src/lib.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/broadcasted_transaction_test.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_6/snapshots/papyrus_rpc__v0_6__write_api_error__write_api_error_test__starknet_error_to_declare_error_snapshot.snap
crates/papyrus_rpc/src/v0_6/snapshots/papyrus_rpc__v0_6__write_api_error__write_api_error_test__starknet_error_to_deploy_account_error_snapshot.snap
crates/papyrus_rpc/src/v0_6/snapshots/papyrus_rpc__v0_6__write_api_error__write_api_error_test__starknet_error_to_invoke_error_snapshot.snap
crates/papyrus_rpc/src/v0_6/transaction_test.rs
crates/papyrus_rpc/src/v0_6/write_api_error_test.rs
crates/papyrus_rpc/src/v0_6/write_api_result_test.rs
crates/papyrus_rpc/src/version_config.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1462)

chore(JSON-RPC): modify files to version 0_6

---

crates/papyrus_monitoring_gateway/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1472)

chore(monitoring): add papyrus_ prefix to process metrics

---

config/default_config.json
crates/papyrus_monitoring_gateway/src/lib.rs
crates/papyrus_node/src/bin/dump_config.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1474)

chore(monitoring): add configurable labels for metrics

---

config/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_storage/src/base_layer.rs
crates/papyrus_storage/src/body/events.rs
crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/compiled_class.rs
crates/papyrus_storage/src/db/db_test.rs
crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/state/mod.rs
crates/papyrus_storage/src/test_utils.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1471)

feat(config): add an `enforce_file_exists` flag to DbConfig + test

---

crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/transaction.rs
crates/papyrus_rpc/src/v0_6/transaction_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1467)

feat(JSON-RPC): support deploy_account V3

---

crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/transaction.rs
crates/test_utils/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1477)

fix(JSON-RPC): fix execution resources schema

---

crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_6/starknet_write_api.json
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/transaction.rs
crates/papyrus_rpc/src/v0_6/transaction_test.rs
crates/starknet_client/src/writer/objects/transaction.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1468)

feat(JSON-RPC): support invoke V3

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1481)

feat(execution, JSON-RPC): pass skip_validation in fee estimation

---

crates/papyrus_common/src/transaction_hash.rs
crates/papyrus_common/src/transaction_hash_test.rs
crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/execution_utils.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/test_utils.rs
crates/papyrus_rpc/src/v0_4/api/mod.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/tests/gateway_integration_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1483)

feat(execution): enforce passing only_query value to execute transaction

---

crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs

- chore(JSON-RPC): merge rpc v0_4 into v0_5 with conflicts
- chore(JSON-RPC): fix conflicts
- chore(JSON-RPC): merge rpc v0_5 into v0_6 with conflicts
- chore(JSON-RPC): fix conflicts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1486)

chore(JSON-RPC): merge rpc v0_5 into v0_6

---

Monitoring/grafana.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1482)

fix(monitoring): fix variables of grafana and add v0_5

---

crates/papyrus_rpc/src/lib.rs
crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_rpc/src/v0_4/block.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/block.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/block.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1490)

fix(JSON-RPC): latest tag means latest block we have its state diff

---

Monitoring/alerts_grafana.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1487)

feat(monitoring): add alerts for unsynced nodes

---

crates/papyrus_common/resources/transaction_hash.json
crates/papyrus_common/src/lib.rs
crates/papyrus_common/src/transaction_hash.rs
crates/papyrus_common/src/transaction_hash_test.rs
crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/tests/gateway_integration_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1488)

feat(common): calculate hash for only-query transactions

---

Cargo.lock
crates/papyrus_execution/Cargo.toml
crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/execution_utils.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_rpc/resources/V0_6/starknet_trace_api_openrpc.json
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/error.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1475)

feat(JSON-RPC, execution): map execution errors according to spec 0.6

---

crates/papyrus_rpc/resources/V0_4/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/src/test_utils.rs
crates/papyrus_rpc/src/v0_4/api/mod.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1494)

test(JSON-RPC): validate schemas of method params

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/state_reader.rs
crates/papyrus_execution/src/state_reader_test.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/api/mod.rs
crates/papyrus_rpc/src/v0_4/error.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_5/error.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/error.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1492)

feat(JSON-RPC): execution works if node is not synced on casms

---

crates/papyrus_execution/src/execution_utils.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/state_reader.rs
crates/papyrus_execution/src/state_reader_test.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1476)

fix(JSON-RPC,execution): look for class hash in replaced classes too

---

crates/papyrus_rpc/src/api.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/api/mod.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1496)

fix(JSON-RPC)!: fix input of starknet_call method

---

crates/papyrus_rpc/tests/gateway_integration_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1497)

test(starknet_client): fix gateway integration test

---

crates/papyrus_rpc/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1500)

test(JSON-RPC): if there are no params, check that the schema expects no params

---

crates/papyrus_rpc/src/test_utils.rs
crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1502)

test(JSON-RPC): validate the name of the parameters we receive in the JsonRpcServer

---

crates/starknet_client/src/reader/mod.rs
crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1504)

fix(starknet_client): query pending block for classes

---

crates/papyrus_rpc/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1505)

test(JSON-RPC): add pretty failure messages for specs tests

---

Monitoring/grafana.json

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1511)

feat(monitoring): add missing panels

---

config/execution/goerli_integration.json
config/execution/goerli_testnet.json
config/execution/mainnet.json
config/execution/sepolia_integration.json
config/execution/sepolia_testnet.json
crates/papyrus_rpc/resources/test_config.json
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1513)

fix(config): fix VM resources cost

---

deployments/helm/values.yaml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1514)

chore(helm): fix presets comment in deployment values

---

crates/papyrus_node/src/version.rs
deployments/helm/backup-values.yaml
deployments/helm/values.yaml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1515)

chore(release): bump version to 0.2.0

---

crates/papyrus_node/src/version.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1516)

chore(release): bump version to 0.3.0-dev

---

crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_execution/src/testing_instances.rs
crates/papyrus_rpc/resources/V0_6/starknet_trace_api_openrpc.json
crates/test_utils/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1498)

feat(execution, JSON-RPC): add execution resources to tx trace

---

crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/block.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1507)

fix(JSON-RPC): validate in execution that the block wasnt reverted mid-execution

---

crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/block.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/block.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs

- chore(JSON-RPC): merge v0_4 into v0_5 until specs test change
- chore(JSON-RPC): merge v0_5 into v0_6 until specs test change
- chore(JSON-RPC): merge v0_4 into v0_5 from specs test change
- chore(JSON-RPC): merge v0_5 into v0_6 from specs test change
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1521)

chore(JSON-RPC): merge versions

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1528)

chore(release): bump crates version to 0.3.0

---

crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_5/transaction.rs
crates/papyrus_rpc/src/v0_6/transaction.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1527)

fix(JSON-RPC): fix serialization of segment_arena

---

crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
crates/papyrus_network/src/streamed_data_protocol/handler.rs
crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
crates/papyrus_network/src/streamed_data_protocol/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1509)

feat(network): session closed by peer event can be for inbound session too

---

README.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1523)

docs(release): add starknet version to readme

---

crates/papyrus_network/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1539)

test(network): add StreamHashMap and a way to create a StreamHashMap of swarms

---

crates/papyrus_network/src/streamed_data_protocol/flow_test.rs
crates/papyrus_network/src/streamed_data_protocol/mod.rs
crates/papyrus_network/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1508)

test(network): add flow test for streamed_data

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_execution/src/test_utils.rs
crates/papyrus_execution/src/testing_instances.rs
crates/papyrus_rpc/resources/V0_6/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/block.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_6/transaction.rs
crates/papyrus_rpc/src/v0_6/transaction_test.rs
crates/papyrus_storage/src/body/events.rs
crates/starknet_client/src/reader/objects/transaction.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1522)

feat(JSON-RPC, execution): add units to the fee

---

crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/api/mod.rs
crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_rpc/src/v0_4/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1541)

fix(JSON-RPC): validate the type of transaction in write api methods

---

crates/papyrus_rpc/src/lib.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_4/transaction.rs
crates/papyrus_rpc/src/v0_4/transaction_test.rs
crates/papyrus_rpc/tests/gateway_integration_test.rs

- fix(JSON-RPC): validate the type of transaction in write api methods
- fix(JSON-RPC): validate that the version field of transaction matches
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1542)

fix(JSON-RPC): validate that the version field of transaction matches

---

crates/starknet_client/src/reader/mod.rs
crates/starknet_client/src/reader/objects/block.rs
crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1548)

feat(starknet_client): block signature data endpoint

---

crates/papyrus_node/src/bin/central_source_integration_test.rs
crates/papyrus_sync/src/lib.rs
crates/papyrus_sync/src/sources/central.rs
crates/papyrus_sync/src/sources/central_sync_test.rs
crates/papyrus_sync/src/sources/central_test.rs
crates/starknet_client/src/reader/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1549)

feat(sync): add block signature to the the block returned from central source

---

crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
crates/papyrus_network/src/streamed_data_protocol/flow_test.rs
crates/papyrus_network/src/streamed_data_protocol/handler.rs
crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
crates/papyrus_network/src/streamed_data_protocol/mod.rs
crates/papyrus_network/src/streamed_data_protocol/protocol.rs
crates/papyrus_network/src/streamed_data_protocol/protocol_test.rs
crates/papyrus_network/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1551)

feat(network): make protocol name configurable

---

crates/papyrus_rpc/resources/V0_4/starknet_trace_api_openrpc.json
crates/papyrus_rpc/resources/V0_5/starknet_trace_api_openrpc.json
crates/papyrus_rpc/resources/V0_6/starknet_trace_api_openrpc.json
crates/papyrus_rpc/src/test_utils.rs
crates/papyrus_rpc/src/v0_4/api/mod.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1552)

test(JSON-RPC): test spec for execution methods

---

Cargo.lock

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1555)

chore(network): update network version in cargo lock

---

crates/papyrus_network/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1563)

chore(network): remove create_swarm

---

crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs

- feat(network): impl From<Inbound/OutboundSessionId> for SessionId
- fix(network): handle ConnectionClosed in streamed_data_protocol::Behaviour
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1559)

fix(network): handle ConnectionClosed in streamed_data_protocol::Behaviour

---

Monitoring/alerts_grafana.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1556)

feat(monitoring): sort alerts by importance

---

crates/papyrus_network/build.rs
crates/papyrus_network/src/messages/messages_test.rs
crates/papyrus_network/src/messages/mod.rs
crates/papyrus_network/src/messages/proto_test/util.proto
crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
crates/papyrus_network/src/streamed_data_protocol/flow_test.rs
crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
crates/papyrus_network/src/streamed_data_protocol/protocol_test.rs
crates/papyrus_network/src/test_utils.rs

- feat(network): impl From<Inbound/OutboundSessionId> for SessionId
- fix(network): handle ConnectionClosed in streamed_data_protocol::Behaviour
- test(network): add BasicMessage to protobuf for testing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1562)

test(network): add BasicMessage to protobuf for testing

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1564)

build(release): update Dockerfile to use rust 1.73

---

crates/papyrus_common/src/transaction_hash.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_4/transaction_test.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_5/transaction_test.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_6/transaction_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1572)

fix(): fix clippy

---

crates/papyrus_storage/src/body/events.rs
crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/db/serialization.rs
crates/papyrus_storage/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1573)

chore(storage): add Key trait

---

crates/papyrus_storage/src/db/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1575)

chore: fix misspelling

---

crates/papyrus_storage/src/body/events.rs
crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/compiled_class.rs
crates/papyrus_storage/src/db/db_test.rs
crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/db/serialization.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/state/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1577)

feat(storage): preparation for versioned values

---

crates/papyrus_storage/src/db/serialization.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1583)

chore(storage): add documentation

---

crates/papyrus_network/src/streamed_data_protocol/handler/session.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1567)

fix(network): wake inbound session when there's a new data

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/block_headers_test.rs
crates/papyrus_network/src/block_headers/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1578)

fix(network): simplify handle_recieved_data

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1580)

chore(network): move functionality into behaviour trait for testing

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1587)

chore(release): bump self (papyrus) version

---

crates/papyrus_rpc/src/v0_4/api/mod.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1554)

fix(JSON-RPC): convert v3 transactions to executable transactions

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1589)

chore: set version to 0.3.0-dev.0 instead of 0.4.0-dev.0

---

crates/papyrus_network/src/block_headers/behaviour.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1588)

feat(network): remove db_executor from block_headers

---

.github/workflows/ci.yml
.github/workflows/nightly-tests.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1585)

ci: move macos jobs to nightly and cleanup protobug install in the CI

---

crates/papyrus_storage/src/db/db_test.rs
crates/papyrus_storage/src/db/serialization.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1584)

feat(storage): add version zero wrapper

---

.github/workflows/ci.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1592)

ci: use setup-protoc action

---

crates/papyrus_network/src/streamed_data_protocol/handler/inbound_session.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1593)

perf(network): remove recursion in InboundSession

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1595)

chore(release): bump crate versions

---

crates/papyrus_sync/src/lib.rs
crates/papyrus_sync/src/sources/central.rs
crates/papyrus_sync/src/sources/central_sync_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1560)

fix(sync): use BlockSignature from SN_API

---

crates/papyrus_storage/src/db/serialization.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/mmap_file/mmap_file_test.rs
crates/papyrus_storage/src/mmap_file/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1599)

feat(storage): support versioned indirect values

---

crates/papyrus_storage/src/db/db_stats.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1565)

feat(storage)!: add free list size to db stat

---

crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_storage/src/body/body_test.rs
crates/papyrus_storage/src/body/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1574)

perf(storage): improve get_block_transaction_count endpoint

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1602)

fix(network): map event function returns option instead of passing the boolean variable arround

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/db_executor.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/messages/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1600)

feat(network): improve send_data readability and use new BlockSignature from starknet_api

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/db_executor.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/messages/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1582)

chore(network): move handle_recieved_data to trait and add tests for it

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1604)

chore(network): cleanup, remove non relevant todos and remove redundent function in trait instead

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1603)

fix(network): handle store_header_pending_pairing_with_signature error

---

crates/papyrus_network/src/block_headers/behaviour_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1607)

chore(network): remove unimplemented tests

---

.github/CODEOWNERS

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1611)

ci: add code owner for .github folder

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/messages/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1610)

chore(network): move protobuf conversion into block header module

---

crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/db_executor/dummy_executor.rs
crates/papyrus_network/src/db_executor/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1609)

chore(network): move db executor to a folder and separate dummy

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/db_executor/dummy_executor.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/messages/mod.rs
crates/papyrus_network/src/streamed_data/behaviour.rs
crates/papyrus_network/src/streamed_data/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1553)

feat(network): add block headers protocol

---

.github/workflows/ci.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1605)

chore: rust nightly upgrade

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin/streamed_data_benchmark.rs
crates/papyrus_network/src/messages/proto_test/util.proto
crates/papyrus_network/src/streamed_data/behaviour.rs
crates/papyrus_network/src/streamed_data/handler.rs
crates/papyrus_network/src/streamed_data/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1591)

build(network): add benchmark executable to streamed_data

---

crates/papyrus_network/src/bin/streamed_data_benchmark.rs

- build(network): add benchmark executable to streamed_data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1596)

build(network): add time from start of session to measurement

---

crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1621)

feat(network): naive network manager implementation

---

crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/bin/streamed_data_benchmark.rs
crates/papyrus_network/src/bin_utils/mod.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1618)

feat(network): create network manager

---

crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/bin/streamed_data_benchmark.rs
crates/papyrus_network/src/bin_utils/mod.rs
crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager.rs
crates/papyrus_network/src/streamed_data/behaviour.rs
crates/papyrus_network/src/streamed_data/behaviour_test.rs
crates/papyrus_network/src/streamed_data/flow_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1617)

feat(network): extract swarm build into bin utils

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/network_manager.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1625)

feat(network): handle db executore restults

---

crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/network_manager.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1626)

fix(network): improve fin handling

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/network_manager.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1624)

feat(network): fix fin handling

---

crates/papyrus_network/src/bin/streamed_data_benchmark.rs

- build(network): clean up benchmark code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1619)

build(network): clean up benchmark code

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin_utils/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1629)

feat(network): allow using both tcp and quic

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/messages/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1628)

feat(network): transition to starknet_api block header type

---

crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/header_test.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serializers.rs
crates/papyrus_sync/src/lib.rs
crates/test_utils/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1561)

feat(storage)!: add block signature table

---

crates/papyrus_common/src/lib.rs
crates/papyrus_common/src/state_diff_commitment.rs
crates/papyrus_common/src/state_diff_commitment_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1570)

feat(common): calculate state diff commitment

---

crates/papyrus_network/src/bin/p2p_integration_endpoint.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1636)

fix(network): use pathfinder's protocol name in integration bin

---

crates/papyrus_network/src/block_headers/behaviour_test.rs
crates/papyrus_network/src/db_executor/dummy_executor.rs
crates/papyrus_network/src/db_executor/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1630)

feat(network): add BlockHeaderDBExecutor and extract common functionality

---

crates/papyrus_storage/src/base_layer.rs
crates/papyrus_storage/src/body/events.rs
crates/papyrus_storage/src/body/events_test.rs
crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/compiled_class.rs
crates/papyrus_storage/src/db/db_test.rs
crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/db/table_types/mod.rs
crates/papyrus_storage/src/db/table_types/simple_table.rs
crates/papyrus_storage/src/db/table_types/simple_table_test.rs
crates/papyrus_storage/src/db/table_types/test_utils.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serializers.rs
crates/papyrus_storage/src/state/mod.rs
crates/papyrus_storage/src/utils.rs
crates/papyrus_storage/src/version.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1518)

refactor(storage): add type for table

---

crates/papyrus_network/src/streamed_data/handler.rs
crates/papyrus_network/src/streamed_data/handler/inbound_session.rs
crates/papyrus_network/src/streamed_data/handler_test.rs
crates/papyrus_network/src/streamed_data/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1640)

revert(network): revert InboundSession checks if outbound closed

---

crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/db_executor/dummy_executor.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/utils.rs
crates/papyrus_network/src/network_manager.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1648)

feat(network): modify db executor to return results by channel

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/db_executor/dummy_executor.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/utils.rs
crates/papyrus_network/src/network_manager.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1633)

feat(network): connect db executor to storage for read

---

crates/papyrus_common/src/transaction_hash.rs
crates/papyrus_sync/src/pending_sync.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1646)

chore: remove imports of macros that prevent the use of evcxr

---

crates/papyrus_network/src/streamed_data/behaviour.rs
crates/papyrus_network/src/streamed_data/behaviour_test.rs
crates/papyrus_network/src/streamed_data/handler.rs
crates/papyrus_network/src/streamed_data/handler_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1644)

feat(network): drop outbound session

---

crates/papyrus_network/src/bin/streamed_data_benchmark.rs

- build(network): clean up benchmark code
- build(network): close benchmark executable when there's no connection for 10 seconds
- build(network): in benchmark, send inbound session messages with round robin
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1622)

build(network): in benchmark, send inbound session messages with round robin

---

crates/papyrus_network/src/bin/streamed_data_benchmark.rs
crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/streamed_data/behaviour.rs
crates/papyrus_network/src/streamed_data/behaviour_test.rs
crates/papyrus_network/src/streamed_data/flow_test.rs
crates/papyrus_network/src/streamed_data/handler.rs
crates/papyrus_network/src/streamed_data/handler_test.rs
crates/papyrus_network/src/streamed_data/mod.rs

- feat(network): drop outbound session
- revert(network): remove close_outbound_session
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1647)

revert(network): remove close_outbound_session

---

crates/papyrus_network/src/bin/streamed_data_benchmark.rs

- build(network): clean up benchmark code
- build(network): close benchmark executable when there's no connection for 10 seconds
- build(network): in benchmark, send inbound session messages with round robin
- build(network): in benchmark, wait for all connections before sending outbound message
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1623)

build(network): in benchmark, wait for all connections before sending outbound message

---

crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/bin/streamed_data_benchmark.rs
crates/papyrus_network/src/bin_utils/mod.rs
crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager.rs
crates/papyrus_network/src/streamed_data/behaviour.rs
crates/papyrus_network/src/streamed_data/behaviour_test.rs
crates/papyrus_network/src/streamed_data/flow_test.rs
crates/papyrus_network/src/streamed_data/handler.rs
crates/papyrus_network/src/streamed_data/handler_test.rs
crates/papyrus_network/src/streamed_data/mod.rs
crates/papyrus_network/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1650)

feat(network): add network config

---

Cargo.lock
crates/papyrus_storage/Cargo.toml
crates/papyrus_storage/src/db/table_types/dup_sort_tables_test.rs
crates/papyrus_storage/src/db/table_types/test_utils.rs

test(storage): add random table test

---

crates/papyrus_network/src/network_manager/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1664)

fix(network): bug in stream collection re-creation

---

crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/db_executor/utils.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1653)

test(network): add db executor tests

---

crates/papyrus_network/src/streamed_data/behaviour.rs
crates/papyrus_network/src/streamed_data/handler.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1671)

chore(network): add TODO to not use VecDeque

---

crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/db_executor/utils.rs
crates/papyrus_network/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1660)

fix(network): add support to block hash in query

---

Monitoring/alerts_grafana.json
deployments/helm/Monitoring/.gitignore
deployments/helm/templates/grafanadashboard.yaml
deployments/install_papyrus.py

- [:heavy_check_mark:] Feature
Currently installations are done via ``helm upgrade`` and do not automatically deploy a grafana dashboard
Instead of directly installing via ``helm upgrade`` we can now use this script which will also tokenize and deploy a grafana dashboard if the deployer wants to have metrics.
-
- [:heavy_check_mark: ] No
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1638)

chore: add papyrus installation script

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1672)

fix(network): reduce exposure of network objects

---

deployments/helm/CI/values.yaml
deployments/helm/templates/grafanadashboard.yaml
deployments/helm/values.yaml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1684)

fix(helm): make grafanadashboard object optional

---

crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_rpc/src/pending.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/starknet_client/src/reader/objects/pending_data.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1685)

feat(execution): set new format of l1_gas_price and l1_data_gas_price

---

Cargo.lock
crates/starknet_client/Cargo.toml
crates/starknet_client/src/reader/mod.rs
crates/starknet_client/tests/feeder_gateway_integration_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1686)

test(starknet_client): add logs to see objects causing serde error in integration test

---

.github/workflows/ci.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1691)

chore: disable clippy

---

crates/papyrus_storage/src/body/events.rs
crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/compiled_class.rs
crates/papyrus_storage/src/db/serialization.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/state/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1678)

feat(storage)!: mark some tables as versioned

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1690)

chore: publish version 0.3.0-rc.0

---

Dockerfile

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1692)

build(release): update Dockerfile to use rust 1.75

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/behaviour_test.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/db_executor/dummy_executor.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/db_executor/utils.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1673)

feat(network): add register_subscriber to network manager

---

crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1667)

feat(network): send fin when encountering DB executor error

---

Cargo.lock
Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs

- feat(network): send fin when encountering DB executor error
- test(network): add test for network manager
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1683)

test(network): add test for network manager

---

crates/starknet_client/resources/reader/block_post_0_13_1.json
crates/starknet_client/resources/reader/old_block_post_0_13_1_no_sn_version.json
crates/starknet_client/src/reader/objects/block.rs
crates/starknet_client/src/reader/objects/block_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1696)

fix(starknet_client): fix deserialization of old blocks post 0.13.1

---

crates/papyrus_node/src/main.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1701)

fix(network): fix is_none config bug

---

crates/papyrus_network/src/streamed_data/behaviour.rs
crates/papyrus_network/src/streamed_data/handler.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1703)

fix(network): wake the poll when a new event is pushed

---

crates/papyrus_network/src/streamed_data/handler/inbound_session.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1702)

refactor(network): improve the flow of the inbound session poll

---

config/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_sync/src/lib.rs
crates/papyrus_sync/src/sources/central.rs
crates/papyrus_sync/src/sources/central_sync_test.rs
crates/papyrus_sync/src/sources/central_test.rs
crates/papyrus_sync/src/sync_test.rs
crates/starknet_client/src/reader/mod.rs
crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1637)

feat(sync): optionally store sequencer pub key and detect if it changes

---

.dockerignore
Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1712)

fix(release): dockerfile copies the lock file

---

Cargo.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1714)

chore: cargo update on cairo lang

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

- chore: bump cairo lang version to 2.6.0-rc.1
- chore: bump crate version to 0.3.0-rc.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1717)

chore: bump crate version to 0.3.0-rc.1

---

crates/papyrus_config/src/presentation.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1706)

chore(config): renames and comments in config presentation

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1720)

fix(release): make sure Cargo.lock isnt erased in Dockerfile

---

deployments/helm/templates/grafanadashboard.yaml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1716)

fix: helm install fix

---

crates/papyrus_config/src/command.rs
crates/papyrus_config/src/config_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1721)

fix(config): set env config params to uppercase alphanumeric + '_'

---

crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1705)

fix(network): small random fixes

---

crates/papyrus_rpc/resources/V0_7/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_7/starknet_trace_api_openrpc.json
crates/papyrus_rpc/resources/V0_7/starknet_write_api.json
crates/papyrus_rpc/src/api.rs
crates/papyrus_rpc/src/lib.rs
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/mod.rs
crates/papyrus_rpc/src/v0_7/api/test.rs
crates/papyrus_rpc/src/v0_7/block.rs
crates/papyrus_rpc/src/v0_7/broadcasted_transaction.rs
crates/papyrus_rpc/src/v0_7/broadcasted_transaction_test.rs
crates/papyrus_rpc/src/v0_7/deprecated_contract_class.rs
crates/papyrus_rpc/src/v0_7/error.rs
crates/papyrus_rpc/src/v0_7/execution_test.rs
crates/papyrus_rpc/src/v0_7/mod.rs
crates/papyrus_rpc/src/v0_7/snapshots/papyrus_rpc__v0_7__write_api_error__write_api_error_test__starknet_error_to_declare_error_snapshot.snap
crates/papyrus_rpc/src/v0_7/snapshots/papyrus_rpc__v0_7__write_api_error__write_api_error_test__starknet_error_to_deploy_account_error_snapshot.snap
crates/papyrus_rpc/src/v0_7/snapshots/papyrus_rpc__v0_7__write_api_error__write_api_error_test__starknet_error_to_invoke_error_snapshot.snap
crates/papyrus_rpc/src/v0_7/state.rs
crates/papyrus_rpc/src/v0_7/transaction.rs
crates/papyrus_rpc/src/v0_7/transaction_test.rs
crates/papyrus_rpc/src/v0_7/write_api_error.rs
crates/papyrus_rpc/src/v0_7/write_api_error_test.rs
crates/papyrus_rpc/src/v0_7/write_api_result.rs
crates/papyrus_rpc/src/v0_7/write_api_result_test.rs
crates/papyrus_rpc/src/version_config.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1725)

chore(JSON-RPC): copy v0_6 into v0_7

---

crates/papyrus_rpc/resources/V0_7/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_7/starknet_trace_api_openrpc.json
crates/papyrus_rpc/resources/V0_7/starknet_write_api.json

- chore(JSON-RPC): copy v0_6 into v0_7
- chore(JSON-RPC): copy v0_7 spec changes that don't require code changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1728)

chore(JSON-RPC): copy v0_7 spec changes that don't require code changes

---

Cargo.lock
Cargo.toml
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_p2p_sync/src/lib.rs
crates/papyrus_p2p_sync/src/p2p_sync_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1722)

feat(sync): add p2p header sync

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1727)

chore: bump version to 0.3.0-rc.2

---

Cargo.lock

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1732)

chore: update lock file

---

crates/papyrus_config/src/config_test.rs
crates/papyrus_config/src/loading.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1735)

fix(config): fix bug with nested optional configs

---

Cargo.lock
config/default_config.json
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1704)

feat(network): add peer id to config

---

Cargo.lock
Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_node/src/bin/dump_config.rs
crates/papyrus_node/src/config/config_test.rs
crates/papyrus_node/src/config/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1733)

test(config): check that the default config file is up-to-date

---

Cargo.lock
crates/papyrus_node/Cargo.toml
crates/papyrus_node/src/main.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1742)

fix(network): fix network error handling in main

---

crates/papyrus_network/src/bin_utils/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1744)

chore(network): add debug printout of the peer address

---

crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/version_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1741)

feat(storage): allow older storage versions

---

Cargo.lock
Cargo.toml
crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_storage/Cargo.toml
crates/papyrus_storage/src/deprecated/migrations.rs
crates/papyrus_storage/src/deprecated/migrations_test.rs
crates/papyrus_storage/src/deprecated/mod.rs
crates/papyrus_storage/src/deprecated/serializers.rs
crates/papyrus_storage/src/deprecated/test_instances.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serialization/mod.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/test_instances.rs
crates/papyrus_sync/src/sources/central.rs
crates/starknet_client/src/reader/objects/block.rs
crates/starknet_client/src/reader/objects/block_test.rs
crates/test_utils/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1718)

feat(storage,starknet_client,sync,test_utils): headers V1 (with migration from V0)

---

crates/starknet_client/src/reader/objects/test_utils.rs
crates/starknet_client/src/reader/objects/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1747)

fix(starknet_client): client can parse ExecutionResources::data_availability

---

config/default_config.json
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1743)

feat(network): add peer address struct to network config

---

crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/test_instances.rs
crates/papyrus_storage/src/version.rs
crates/papyrus_storage/src/version_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1749)

feat(storage)!: add major and minor storage versions

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1758)

chore: bump crate version to 0.3.0-rc.3

---

crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_rpc/src/v0_4/transaction.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_7/api/test.rs
crates/test_utils/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1760)

test(JSON-RPC): make test randomize also on execution status

---

crates/papyrus_p2p_sync/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1753)

feat(network): add block id status info printout in p2p sync

---

crates/papyrus_network/src/network_manager/swarm_trait.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1754)

fix(network): swarm trait dial address construction fix

---

crates/papyrus_execution/src/objects.rs
crates/papyrus_rpc/resources/V0_7/starknet_api_openrpc.json
crates/papyrus_rpc/src/api.rs
crates/papyrus_rpc/src/test_utils.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/mod.rs
crates/papyrus_rpc/src/v0_7/api/test.rs
crates/papyrus_rpc/src/v0_7/execution_test.rs
crates/papyrus_rpc/src/v0_7/transaction.rs
crates/starknet_client/src/reader/objects/pending_data.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1734)

feat(JSON-RPC): getBlockWithReceipts

---

config/default_config.json
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1756)

fix(network): make peer_id non optional

---

crates/papyrus_p2p_sync/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1764)

feat(network): p2p sync semi handle other peer finished

---

crates/papyrus_network/src/network_manager/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1763)

fix(network): wrong peer id dial crash bug

---

crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/converters/mod.rs
crates/papyrus_network/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1765)

refactor(network): move to converters-protobuf::SignedBlockHeader to network SignedBlockHeader

---

crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/converters/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1766)

refactor(network): move to converters-starknetapi Header & Signature to protobuf SignedBlockHeader

---

crates/papyrus_network/src/block_headers/mod.rs
crates/papyrus_network/src/converters/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1768)

refactor(network): move to converters-starknet api BlockSignature to protobuf ConsesusSignature

---

crates/papyrus_network/src/block_headers/behaviour.rs
crates/papyrus_network/src/block_headers/flow_test.rs
crates/papyrus_network/src/converters/mod.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1770)

feat(network): data blockHeaderAndSignature sigs to vec

---

crates/papyrus_network/src/bin/p2p_integration_endpoint.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1771)

fix(network): uncomment p2p integration endpoint

---

crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/mod.rs
crates/papyrus_rpc/src/v0_6/execution.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_6/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1775)

fix(JSON-RPC): fix serialization of trace in v0.6

---

crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/mod.rs
crates/papyrus_rpc/src/v0_5/execution.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_5/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1774)

fix(JSON-RPC): fix serialization of trace in v0.5

---

crates/papyrus_network/src/converters/mod.rs
crates/papyrus_network/src/network_manager/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1737)

feat(network): handle try_send error from net manager to subscriber

---

crates/papyrus_rpc/src/v0_7/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1777)

feat(JSON-RPC): add data availability fields to execution resources

---

crates/papyrus_rpc/src/v0_7/transaction.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1778)

feat(JSON-RPC): impl Add for ExecutionResources

---

crates/papyrus_rpc/resources/V0_7/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/test.rs
crates/papyrus_rpc/src/v0_7/block.rs
crates/starknet_client/src/reader/objects/pending_data.rs

- feat(JSON-RPC): move code
- feat(JSON-RPC): getBlockWithReceipts
- feat(JSON-RPC): add da fields to header
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1751)

feat(JSON-RPC): add da fields to header

---

crates/papyrus_rpc/src/v0_7/execution.rs
crates/papyrus_rpc/src/v0_7/mod.rs

- feat(JSON-RPC): add TransactionTrace for v0_7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1779)

feat(JSON-RPC): add TransactionTrace for v0_7

---

crates/papyrus_rpc/src/v0_7/execution.rs
crates/papyrus_rpc/src/v0_7/state.rs

- feat(JSON-RPC): add TransactionTrace for v0_7
- feat(JSON-RPC): sort state diff in trace
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1780)

feat(JSON-RPC): sort state diff in trace

---

README.adoc

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1665)

docs: fixed API request example

---

crates/papyrus_network/src/converters/protobuf_conversion.rs
crates/papyrus_network/src/protobuf_messages/mod.rs

- refactor(network): move code around
- refactor(network): change streamed_data to streamed_bytes
- feat(network): convert network manager to work on bytes
- style(network): rename stream_bytes GenericEvent to Event
- feat(network): handle try_send error from net manager to subscriber
- feat(network): more detailed ProtobufConversionError
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1745)

feat(network): more detailed ProtobufConversionError

---

crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1788)

feat(network): chain fin to query receiver

---

crates/papyrus_rpc/resources/V0_7/starknet_api_openrpc.json
crates/papyrus_rpc/resources/V0_7/starknet_trace_api_openrpc.json
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/mod.rs
crates/papyrus_rpc/src/v0_7/execution_test.rs
crates/test_utils/src/lib.rs

- feat(JSON-RPC): add TransactionTrace for v0_7
- feat(JSON-RPC): sort state diff in trace
- fix(JSON-RPC): use rpc's TransactionTrace in api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1781)

fix(JSON-RPC): use rpc's TransactionTrace in api

---

crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1789)

feat(network): db executor support for data types with a new trait

---

Cargo.lock
Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_network/build.rs
crates/papyrus_network/src/converters/protobuf_conversion/mod.rs
crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs
crates/papyrus_network/src/protobuf_messages/proto/p2p/proto/state.proto

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1792)

feat(network): add conversion from protobuf::StateDiffsResponse to ThinStateDiff

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_execution/src/testing_instances.rs
crates/papyrus_rpc/resources/V0_7/starknet_api_openrpc.json
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/mod.rs
crates/papyrus_rpc/src/v0_7/execution_test.rs

- feat(JSON-RPC): add TransactionTrace for v0_7
- feat(JSON-RPC): sort state diff in trace
- fix(JSON-RPC): use rpc's TransactionTrace in api
- feat(JSON-RPC): in v0_7, return detailed fee estimation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1783)

feat(JSON-RPC): in v0_7, return detailed fee estimation

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/converters/protobuf_conversion/header.rs
crates/papyrus_network/src/converters/protobuf_conversion/mod.rs
crates/papyrus_network/src/converters/test.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1790)

feat(network): add support for state diff in db executor (not in net manager yet)

---

crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1791)

feat(network): get data type dynamically based on protocol name

---

crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/objects.rs
crates/papyrus_execution/src/test_utils.rs
crates/papyrus_rpc/src/pending.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1784)

fix(JSON-RPC): set use_kzg_da correctly

---

crates/papyrus_node/src/version.rs

- chore: change node version to stable (0.3.0)
- chore: change node version to 0.4.0 dev
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1797)

chore: change node version to 0.4.0 dev

---

crates/papyrus_rpc/src/api.rs
crates/papyrus_rpc/src/test_utils.rs
crates/papyrus_rpc/src/v0_4/api/api_impl.rs
crates/papyrus_rpc/src/v0_4/api/test.rs
crates/papyrus_rpc/src/v0_4/execution_test.rs
crates/papyrus_rpc/src/v0_5/api/api_impl.rs
crates/papyrus_rpc/src/v0_5/api/test.rs
crates/papyrus_rpc/src/v0_5/execution_test.rs
crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_6/execution_test.rs
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/test.rs
crates/papyrus_rpc/src/v0_7/execution_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1759)

refactor(JSON-RPC): rename JsonRpcServerV*Impl to JsonRpcServerImpl

---

crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs

- feat(network): add conversion from protobuf::StateDiffsResponse to ThinStateDiff
- feat(network): add conversion from ThinStateDiff to protobuf::StateDiffsResponse
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1793)

feat(network): add conversion from ThinStateDiff to protobuf::StateDiffsResponse

---

crates/papyrus_common/src/block_hash.rs
crates/papyrus_common/src/transaction_hash.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1799)

fix(common): avoid calculating unnecessary branches in hashchains

---

crates/papyrus_network/src/converters/mod.rs
crates/papyrus_network/src/converters/protobuf_conversion/common.rs
crates/papyrus_network/src/converters/protobuf_conversion/header.rs
crates/papyrus_network/src/converters/protobuf_conversion/mod.rs
crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_p2p_sync/src/lib.rs
crates/papyrus_p2p_sync/src/p2p_sync_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1801)

feat(network): network manager support for multiple protocols

---

crates/papyrus_sync/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1785)

fix(starknet_client): make pending error recoverable and refactor

---

crates/papyrus_p2p_sync/src/header.rs
crates/papyrus_p2p_sync/src/stream_factory.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1806)

fix(sync): write_to_storage consumes the object

---

crates/starknet_client/src/reader/objects/block.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1807)

fix(starknet_client): deprecated l1 gas price wei and fri mistake

---

Cargo.lock
Cargo.toml
crates/papyrus_network/src/converters/protobuf_conversion/header.rs
crates/papyrus_storage/src/deprecated/migrations.rs
crates/papyrus_storage/src/deprecated/migrations_test.rs
crates/papyrus_storage/src/deprecated/serializers.rs
crates/papyrus_storage/src/deprecated/test_instances.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/test_instances.rs
crates/starknet_client/src/reader/objects/block.rs
crates/test_utils/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1811)

chore: add state_diff_length, receipt_commitment to BlockHeader from SN API

---

crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
crates/papyrus_network/src/network_manager/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1808)

refactor: remove dial from NetworkManager

---

config/execution/goerli_integration.json
config/execution/goerli_testnet.json
config/execution/mainnet.json
config/execution/sepolia_integration.json
config/execution/sepolia_testnet.json
crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs
crates/papyrus_execution/src/testing_instances.rs
crates/papyrus_rpc/resources/test_config.json

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1750)

refactor: add strk fee contract address into config

---

Cargo.lock
crates/papyrus_load_test/Cargo.toml
crates/papyrus_load_test/src/create_files.rs
crates/papyrus_load_test/src/main.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1752)

feat(load_test)!: use url instead of port when creating files

---

README.adoc
crates/papyrus_monitoring_gateway/src/gateway_test.rs
crates/papyrus_monitoring_gateway/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_node/src/main.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1809)

feat(monitoring): report peer id in monitoring gateway

---

crates/papyrus_common/src/state_diff_commitment.rs
crates/papyrus_common/src/state_diff_commitment_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1825)

chore(common): use StateDiffCommitment type

---

crates/papyrus_network/src/db_executor/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1820)

fix(network): return correct type of fin for state diff in db executor

---

crates/papyrus_network/src/db_executor/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1821)

fix(network): add state_diff_length to header in db executor

---

crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1817)

fix(node): register to state diff when registering network subscribers

---

crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1823)

fix(network): fill missing Protocol::StateDiff in the network manager

---

crates/papyrus_network/src/bin/streamed_bytes_benchmark.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/streamed_bytes/behaviour.rs
crates/papyrus_network/src/streamed_bytes/behaviour_test.rs
crates/papyrus_network/src/streamed_bytes/flow_test.rs
crates/papyrus_network/src/streamed_bytes/handler/inbound_session.rs
crates/papyrus_network/src/streamed_bytes/handler_test.rs
crates/papyrus_network/src/streamed_bytes/messages.rs
crates/papyrus_network/src/streamed_bytes/messages_test.rs
crates/papyrus_network/src/streamed_bytes/mod.rs
crates/papyrus_network/src/streamed_bytes/protocol_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1824)

fix(network): add prefix to data in network manager instead of behaviour

---

crates/papyrus_storage/src/mmap_file/mmap_file_test.rs
crates/papyrus_storage/src/mmap_file/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1833)

fix(storage): clippy fix

---

crates/papyrus_storage/src/mmap_file/mmap_file_test.rs
crates/papyrus_storage/src/mmap_file/mod.rs
crates/starknet_client/tests/feeder_gateway_integration_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1835)

chore: fix clippy failures for rust 1.77.0

---

crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/streamed_bytes/behaviour.rs
crates/papyrus_network/src/streamed_bytes/handler.rs
crates/papyrus_network/src/test_utils/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1831)

chore(network): dead code attributes cleanup

---

Cargo.lock

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1843)

chore: update cargo.lock file

---

crates/papyrus_load_test/src/compare_endpoints.rs
crates/papyrus_load_test/src/create_request.rs
crates/papyrus_load_test/src/transactions.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1839)

feat(load_test): add getBlockWithReceipts endpoint to the load test

---

README.adoc
crates/papyrus_common/src/metrics.rs
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1840)

chore(network): add num_connected_peers metric

---

crates/papyrus_execution/resources/versioned_constants_13_0.json
crates/papyrus_execution/src/execution_test.rs
crates/papyrus_execution/src/lib.rs

This reverts commit 009737aa250d1753d1f1424a33463dcda6d42b11.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1847)

feat(execution): undo remove of 0.13.0 support

---

crates/papyrus_p2p_sync/src/state_diff.rs
crates/papyrus_rpc/src/v0_7/api/test.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/state/mod.rs
crates/papyrus_storage/src/state/state_test.rs
crates/papyrus_storage/src/test_instances.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1846)

feat(storage)!: add functionality to write thin state diff

---

crates/papyrus_common/src/metrics.rs
crates/papyrus_network/src/network_manager/mod.rs

- chore(network): add num_connected_peers metric
- chore(network): add num_active_inbound/outbound_sessions metric
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1841)

chore(network): add num_active_inbound/outbound_sessions metric

---

crates/papyrus_monitoring_gateway/src/gateway_test.rs
crates/papyrus_monitoring_gateway/src/lib.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/mmap_file/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1830)

feat(storage, monitoring): mmap files stats

---

config/presets/goerli_integration.json
config/presets/goerli_testnet.json
config/presets/mainnet.json
config/presets/sepolia_integration.json
config/presets/sepolia_testnet.json

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1852)

revert(config): revert back to presets

---

crates/papyrus_storage/src/test_utils.rs
crates/papyrus_storage/src/version_test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1810)

test(storage): more tests for major storage version

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1869)

chore: publish v0.4.0-dev.0

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1873)

chore: publish v0.4.0-dev.1 (dev.0 was yanked in the past)

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1854)

feat(network): close inbound session after sending fin

---

deployments/helm/values.yaml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1871)

chore: remove goerli from deployment yaml

---

crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1858)

fix(network): register and use channel test

---

config/presets/goerli_integration.json
config/presets/goerli_testnet.json

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1861)

chore(config): remove goerli presets

---

crates/papyrus_storage/Cargo.toml
papyrus_utilities.Dockerfile

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1855)

chore(storage)!: make dependecies of binaries in the storage optional

---

crates/papyrus_storage/src/state/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1876)

doc(storage): fix minor doc comment

---

crates/papyrus_storage/src/class.rs
crates/papyrus_storage/src/class_test.rs

- feat(storage): add read/write functionality for classes
- fix(storage): append_classes can receive classes not from the state diff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1875)

fix(storage): append_classes can receive classes not from the state diff

---

crates/papyrus_storage/src/state/state_test.rs
crates/papyrus_storage/src/utils_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1877)

refactor(storage): remove usage of append_state_diff from storage tests (except revert tests)

---

crates/papyrus_network/src/network_manager/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1889)

fix(network): lister to incomming requests from worldwide

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
crates/papyrus_network/src/main_behaviour/mod.rs
crates/papyrus_network/src/streamed_bytes/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1888)

feat(network): add skeleton for MainBehaviour

---

crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/test_instances.rs

- feat(storage)!: add functionality to write thin state diff
- feat(storage)!: add markers to events and receipts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1848)

feat(storage)!: add marker to events

---

crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1896)

feat(network): mixed beahviour event

---

crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1899)

feat(network): add BridgedBehaviour trait

---

crates/papyrus_config/src/dumping.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1893)

docs(config): add examples for using pointer params

---

crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
crates/papyrus_network/src/main_behaviour/mod.rs
crates/papyrus_network/src/streamed_bytes/behaviour.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1902)

feat(network): add streamed bytes internal event

---

crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/peer.rs
crates/papyrus_network/src/peer_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1904)

feat(network): peer manager behaviour

---

papyrus_utilities.Dockerfile

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1883)

chore: fix and setting app to working directory in papyrus_utilities

---

crates/papyrus_network/src/discovery/identify_impl.rs
crates/papyrus_network/src/discovery/kad_impl.rs
crates/papyrus_network/src/discovery/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
crates/papyrus_network/src/main_behaviour/mod.rs
crates/papyrus_network/src/streamed_bytes/behaviour.rs

- feat(network): add BridgedBehaviour trait
- feat(network): add discovery behaviour
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1903)

feat(network): add discovery behaviour

---

.github/workflows/ci.yml
papyrus_utilities.Dockerfile

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1882)

ci: build papyrus_utilities in the ci

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/starknet_client/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1907)

chore: bump crates versions to 0.4.0-dev.2

---

crates/papyrus_network/src/peer_manager/behaviour_impl.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1905)

feat(network): handle on_swarm_event in peer management

---

Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1910)

chore: add ppyrus_common to the workspace members

---

crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/peer.rs
crates/papyrus_network/src/peer_manager/test.rs
crates/papyrus_network/src/streamed_bytes/behaviour.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1908)

feat(network): peer manager hadles dial

---

crates/papyrus_network/src/discovery/mod.rs
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1912)

feat(network): pm pasue discovery

---

crates/papyrus_network/src/peer_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1916)

fix(network): pause discovery test

---

.github/workflows/ci.yml
.github/workflows/nightly-tests.yml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1866)

chore!: make binaries dependecies optional

---

crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
crates/papyrus_network/src/main_behaviour/mod.rs
crates/papyrus_network/src/peer_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1918)

feat(network): add FromOtherBehaviour to PeerManager

---

crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/test.rs
crates/papyrus_network/src/streamed_bytes/behaviour.rs

- feat(network): add FromOtherBehaviour to PeerManager
- feat(network): add connection_id to SessionAssigned
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1919)

feat(network): add connection_id to SessionAssigned

---

crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/discovery/mod.rs

- feat(network): add discovery behaviour
- test(network): add discovery unit tests
- feat(network): discovery dials to bootstrap node
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1909)

feat(network): discovery dials to bootstrap node

---

.github/workflows/ci.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1922)

fix:  use token for codecov in ci

---

crates/papyrus_network/src/bin/streamed_bytes_benchmark.rs
crates/papyrus_network/src/bin_utils/mod.rs
crates/papyrus_network/src/discovery/kad_impl.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/peer_manager/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1921)

feat(network): mixed behaviour in network manager

---

README.adoc

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1860)

chore: remove goerli references from readme

---

config/default_config.json
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

refactor(network): replace peeraddrconfig
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1851)

refactor(network): replace peeraddrconfig with multiaddress

---

crates/papyrus_storage/src/bin/README.md
crates/papyrus_storage/src/bin/dump_declared_classes.rs
crates/papyrus_storage/src/bin/storage_benchmark.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1872)

chore: remove goerli from storage

---

config/default_config.json
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
crates/papyrus_network/src/main_behaviour/mod.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1924)

feat(network): add bootstrap node to config

---

crates/papyrus_network/src/network_manager/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1926)

feat(network): catch more swarm events in network manager

---

crates/papyrus_network/src/network_manager/swarm_trait.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1929)

feat(network): use start_query in swarm trait

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/streamed_bytes/behaviour.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1928)

feat(network): add tracing info to behaviours

---

crates/papyrus_network/src/network_manager/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1934)

fix(network): remove unneeded failing test

---

crates/papyrus_network/src/discovery/mod.rs
crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_node/src/version.rs
crates/papyrus_rpc/src/version_config.rs
crates/papyrus_storage/src/db/table_types/simple_table.rs
crates/papyrus_storage/src/state/mod.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1933)

refactor: remove unnecessary dead_code annotations

---

crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/api_impl.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1942)

style(JSON-RPC): delete consider todos after consider

---

crates/papyrus_storage/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1941)

docs(storage): document storage version

---

crates/papyrus_storage/src/bin/storage_benchmark.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1943)

fix(storage): db_file_path to db_path in storage benchmark

---

crates/papyrus_network/src/lib.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1944)

fix(network): increase session timeout defaults

---

crates/papyrus_network/src/peer_manager/behaviour_impl.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1945)

fix(network): dont retry dial if another is active

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1938)

feat(network): add listener addresses as external addresses

---

crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/discovery/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1930)

feat(network): call Kad::add_address on bootstrap peer

---

crates/papyrus_rpc/src/test_utils.rs
crates/papyrus_rpc/src/v0_6/api/test.rs
crates/papyrus_rpc/src/v0_7/api/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1892)

chore(test_utils): replace chain id from goerli to sepolia

---

README.adoc

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1881)

docs: fix example api request

---

crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1946)

fix: config test

---

crates/papyrus_network/src/peer_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1932)

feat(network): log peers added and blacklisted

---

crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1950)

fix(network): PM will assign peer once it has if received session on no peers

---

crates/papyrus_network/src/peer_manager/behaviour_impl.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1951)

fix(network): add connection id to new peer

---

crates/papyrus_rpc/src/v0_6/transaction_test.rs
crates/papyrus_rpc/src/v0_7/transaction_test.rs

…in rpc tests
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1949)

chore(test_utils): replace goerli l1handler transaction with mainnet

---

crates/papyrus_load_test/src/main.rs
crates/papyrus_storage/src/bin/storage_benchmark.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1957)

fix: change units to unit in the storage benchmark and load test

---

.github/workflows/ci.yml

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1958)

chore: fix ci random table test

---

commitlint.config.js

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1960)

chore(block_builder): add block builder scope

---

crates/papyrus_rpc/Cargo.toml
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/api/mod.rs
crates/papyrus_rpc/src/v0_7/api/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1954)

feat(JSON-RPC): add getCompiledContractClass support

---

crates/papyrus_common/src/block_hash.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1915)

fix(common): fix v2 tx commitment calculation

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Dockerfile
crates/sequencing/papyrus_block_builder/Cargo.toml
crates/sequencing/papyrus_block_builder/src/lib.rs
crates/sequencing/papyrus_block_builder/src/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1961)

feat(block_builder): initial mock block builder

---

crates/sequencing/papyrus_block_builder/src/test.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1970)

chore(block_builder): add TODO for test coverage

---

Cargo.lock
crates/papyrus_node/Cargo.toml
crates/papyrus_node/examples/get_transaction_hash.rs

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1959)

chore(node): make get transaction hash example async

---

crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/discovery/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1967)

fix(network): sleep before redialing to bootstrap peer

---

crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/serialization/serializers_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1972)

perf(storage)!: serialize BlockNumber as 32-bit

---

crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/serialization/serializers_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1973)

perf(storage)!: serialized TransactionOffsetInBlock as three bytes

---

crates/papyrus_storage/src/mmap_file/mmap_file_test.rs
crates/papyrus_storage/src/mmap_file/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1974)

perf(storage)!: improve serialization of location in file

---

crates/papyrus_network/src/discovery/discovery_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1975)

test(network): test discovery doesn't redial after DIAL_SLEEP - epsilon

---

crates/papyrus_network/build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1991)

feat(network): ensure protoc version >=3.15

---

crates/papyrus_storage/src/body/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1999)

style(storage): use iter instead of loop

---

crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1995)

refactor(network): remove return value from assign peer to session

---

.github/workflows/benchmark.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2012)

chore: run storage benchmark only in workflow dispatch

---

crates/papyrus_network/src/discovery/flow_test.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/streamed_bytes/flow_test.rs
crates/papyrus_network/src/test_utils/mod.rs
crates/papyrus_network/src/utils.rs
crates/papyrus_network/src/utils/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2006)

refactor(network): make StreamHashMap usable in source code (not tests only)

---

Cargo.lock
Cargo.toml
commitlint.config.js
crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/lib.rs

**Stack**:
- #1993
- #1992 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1992)

feat(consensus): create consensus crate

---

crates/papyrus_network/src/discovery/discovery_test.rs
crates/papyrus_network/src/discovery/flow_test.rs
crates/papyrus_network/src/discovery/identify_impl.rs
crates/papyrus_network/src/discovery/kad_impl.rs
crates/papyrus_network/src/discovery/mod.rs
crates/papyrus_network/src/mixed_behaviour.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/test.rs
crates/papyrus_network/src/streamed_bytes/behaviour.rs
crates/papyrus_network/src/streamed_bytes/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1979)

refactor(network): change inter behaviour events to be sender based not consumer based

---

crates/papyrus_network/src/converters/protobuf_conversion/common.rs
crates/papyrus_network/src/converters/protobuf_conversion/header.rs
crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs
crates/papyrus_network/src/protobuf_messages/proto/p2p/proto/common.proto
crates/papyrus_network/src/protobuf_messages/proto/p2p/proto/header.proto
crates/papyrus_network/src/protobuf_messages/proto/p2p/proto/state.proto

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1998)

feat(network): add common.proto

---

crates/papyrus_network/src/broadcast/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2018)

feat(network): add register_broadcast_subscribers without connecting to behaviour

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from DeployAccountTransactionV1 to protobuf DeployAccountV1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2005)

feat(network): add conversion from DeployAccountTransactionV1 to protobuf DeployAccountV1

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from protobuf::ResourceBounds to ResourceBoundsMapping
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2007)

feat(network): add conversion from protobuf::ResourceBounds to ResourceBoundsMapping

---

crates/papyrus_network/src/broadcast/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1981)

feat(network): add broadcast behaviour with unimplemented

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from DeployAccountTransactionV3 to protobuf DeployAccountV3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2009)

feat(network): add conversion from protobuf DeployAccountV3 to DeployAccountTransactionV3

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from DeployAccountTransactionV3 to protobuf DeployAccountV3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2010)

feat(network): add conversion from DeployAccountTransactionV3 to protobuf DeployAccountV3

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from protobuf InvokeV0 to InvokeTransactionV0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2011)

feat(network): add conversion from protobuf InvokeV0 to InvokeTransactionV0

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from InvokeTransactionV0 to protobuf InvokeV0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2013)

feat(network): add conversion from InvokeTransactionV0 to protobuf InvokeV0

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from protobuf InvokeV1 to InvokeTransactionV1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2014)

feat(network): add conversion from protobuf InvokeV1 to InvokeTransactionV1

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from InvokeTransactionV1 to protobuf InvokeV1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2015)

feat(network): add conversion from InvokeTransactionV1 to protobuf InvokeV1

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from protobuf InvokeV3 to InvokeTransactionV3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2016)

feat(network): add conversion from protobuf InvokeV3 to InvokeTransactionV3

---

crates/papyrus_rpc/src/v0_6/api/api_impl.rs
crates/papyrus_rpc/src/v0_6/transaction.rs
crates/papyrus_rpc/src/v0_7/api/api_impl.rs
crates/papyrus_rpc/src/v0_7/transaction.rs
crates/papyrus_storage/src/body/body_test.rs
crates/papyrus_storage/src/body/events.rs
crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/db/table_types/mod.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/test_utils/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2000)

perf(storage)!: store event inside transaction output

---

crates/papyrus_network/src/network_manager/test.rs

- feat(network): add register_broadcast_subscribers without connecting to behaviour
- feat(network): connect broadcast subscribers to behaviour
- test(network): add tests for broadcast subscriber in network manager
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1987)

test(network): add tests for broadcast subscriber in network manager

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from protobuf DeclareV0 to DeclareTransactionV0V1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2020)

feat(network): add conversion from protobuf DeclareV0 to DeclareTransactionV0V1

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from DeclareTransactionV0V1 to protobuf DeclareV0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2021)

feat(network): add conversion from DeclareTransactionV0V1 to protobuf DeclareV0

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from protobuf DeclareV1 to DeclareTransactionV0V1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2023)

feat(network): add conversion from protobuf DeclareV1 to DeclareTransactionV0V1

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from DeclareTransactionV0V1 to protobuf DeclareV1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2024)

feat(network): add conversion from DeclareTransactionV0V1 to protobuf DeclareV1

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from protobuf DeclareV2 to DeclareTransactionV2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2025)

feat(network): add conversion from protobuf DeclareV2 to DeclareTransactionV2

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from DeclareTransactionV2 to protobuf DeclareV2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2026)

feat(network): add conversion from DeclareTransactionV2 to protobuf DeclareV2

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from protobuf DeclareV3 to DeclareTransactionV3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2027)

feat(network): add conversion from protobuf DeclareV3 to DeclareTransactionV3

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

feat(network): add conversion from DeclareTransactionV3 to protobuf DeclareV3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2028)

feat(network): add conversion from DeclareTransactionV3 to protobuf DeclareV3

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2034)

feat(network): add conversion from protobuf Deploy to DeployTransaction

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2035)

feat(network): add conversion from DeployTransaction to protobuf Deploy

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2036)

feat(network): add conversion from protobuf L1HandlerV0 to L1HandlerTransaction

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2037)

feat(network): add conversion from L1HandlerTransaction to protobuf L1HandlerV0

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2038)

feat(network): add conversion from protobuf txn to Transaction

---

crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2039)

feat(network): add conversion from Transaction to protobuf txn

---

crates/papyrus_network/src/converters/protobuf_conversion/mod.rs
crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2043)

feat(network): add conversion between protobuf BuiltinCounter and HashMap<Builtin, u64>

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2045)

feat(network): add conversion between protobuf EthereumAddress and EthAddress

---

crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2046)

feat(network): add conversion between protobuf MessageToL1 and sn api

---

crates/papyrus_network/src/converters/protobuf_conversion/common.rs
crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs
crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2047)

feat(network): add conversion from protobuf::receipt::DeployAccount to sn api

---

crates/papyrus_network/src/converters/protobuf_conversion/receipt.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2052)

refactor(network): fix PR #2047

---

crates/papyrus_network/src/network_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2057)

chore(network): fix PR 2041 comments

---

crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/src/header_test.rs
crates/papyrus_p2p_sync/src/lib.rs
crates/papyrus_p2p_sync/src/state_diff_test.rs
crates/papyrus_p2p_sync/src/stream_factory.rs
crates/papyrus_p2p_sync/src/test_utils.rs

- chore(network): unite Data with SignedBlockHeader
- refactor(network): remove data_type from Query
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2042)

refactor(network): remove data_type from Query

---

crates/papyrus_network/src/converters/protobuf_conversion/common.rs
crates/papyrus_network/src/converters/protobuf_conversion/header.rs
crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/db_executor/utils.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_p2p_sync/src/header_test.rs
crates/papyrus_p2p_sync/src/lib.rs
crates/papyrus_p2p_sync/src/state_diff_test.rs
crates/papyrus_p2p_sync/src/stream_factory.rs
crates/papyrus_p2p_sync/src/test_utils.rs

- chore(network): unite Data with SignedBlockHeader
- refactor(network): remove data_type from Query
- refactor(network): remove InternalQuery
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2048)

refactor(network): remove InternalQuery

---

crates/papyrus_protobuf/src/converters/header.rs
crates/papyrus_protobuf/src/converters/header_test.rs
crates/papyrus_protobuf/src/converters/mod.rs
crates/papyrus_protobuf/src/converters/state_diff.rs
crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2060)

feat(network): add macro for impl TryFrom<Vec<u8>> and Into<Vec<u8>> and use it in query

---

crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2061)

feat(network): add state diff part struct identical to protobuf

---

crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2030)

refactor(network): rename register_subscriber to register_sqmr_subscriber

---

crates/papyrus_storage/src/db/serialization.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2065)

fix(storage): check eof for all deserailzations

---

crates/papyrus_protobuf/src/converters/transaction.rs
crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2056)

feat(network): add conversion between protobuf TransactionsResponse and sn api

---

crates/papyrus_protobuf/src/converters/header.rs
crates/papyrus_protobuf/src/converters/header_test.rs
crates/papyrus_protobuf/src/converters/state_diff.rs
crates/papyrus_protobuf/src/converters/transaction.rs
crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2070)

feat(protobuf): add one struct for all sync responses types

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2059)

feat(consensus): add validator flow to SingleHeightConsensus

---

crates/papyrus_protobuf/build.rs
crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/converters/mod.rs
crates/papyrus_protobuf/src/lib.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2068)

feat(protobuf): add consenus proposal to protobuf

---

crates/papyrus_network/src/converters/mod.rs
crates/papyrus_protobuf/src/converters/state_diff.rs

- feat(protobuf): add one struct for all sync responses types
- feat(network): add conversion from Vec<u8> to DataOrFin<ThinStateDiff>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2071)

feat(network): add conversion from Vec<u8> to DataOrFin<ThinStateDiff>

---

crates/papyrus_storage/src/serialization/serializers.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2072)

perf(storage)!: compress transaction outputs

---

crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2067)

feat(network): change fetch_block_data_from_db return output to Vec<Data>

---

crates/papyrus_config/src/converters.rs
crates/papyrus_config/src/validators.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2075)

feat(config): add serde option for vector configurations

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2082)

feat(network): replace ThinStateDiff with StateDiffChunk in db_executor Data

---

crates/papyrus_common/resources/transaction_hash.json

-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1965)

test(common): add declare tx v0, v3 to transaction_hash.js

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto

Also add converters to make them convertable from/to Bytes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2077)

feat(consensus): update the protobuf with ConsensusMessage which will wrap all consensus messages

---

crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/types.rs

While not yet set in stone this is the leading contender and matches what is defined in the proto.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2078)

feat(consensus): set NodeId to ContractAddress

---

crates/papyrus_storage/src/db/table_types/dup_sort_tables.rs
crates/papyrus_storage/src/db/table_types/mod.rs
crates/papyrus_storage/src/db/table_types/simple_table.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2074)

style(storage): documentation changes to table types

---

Cargo.lock
config/default_config.json
crates/papyrus_config/src/lib.rs
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin/streamed_bytes_benchmark.rs
crates/papyrus_network/src/bin_utils/mod.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2087)

feat(network): consistent peer id functionality

---

crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/db_executor/utils.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs

- feat(network): remove stream in DBExecutorTrait
- WIP
- refactor(network): remove QueryId from db executor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2095)

refactor(network): remove QueryId from db executor

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/sequencing/papyrus_block_builder/Cargo.toml
crates/starknet_client/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2097)

chore: bump crates version to 0.4.0-dev.3

---

crates/papyrus_network/src/bin/streamed_bytes_benchmark.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/sqmr/behaviour.rs
crates/papyrus_network/src/sqmr/behaviour_test.rs
crates/papyrus_network/src/sqmr/flow_test.rs
crates/papyrus_network/src/sqmr/handler.rs
crates/papyrus_network/src/sqmr/handler_test.rs
crates/papyrus_network/src/sqmr/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2098)

refactor(network): report callback for received data

---

Cargo.lock
crates/papyrus_protobuf/Cargo.toml
crates/papyrus_protobuf/build.rs
crates/papyrus_protobuf/src/converters/class.rs
crates/papyrus_protobuf/src/converters/mod.rs
crates/papyrus_protobuf/src/proto/p2p/proto/class.proto

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2100)

feat(network): add conversion between protobuf Class and sn api

---

Cargo.lock
crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/lib.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2079)

refactor(consensus): the SHC goes from a task to an object which is called directly

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2083)

ci: cache layers when building papyrus utilities image

---

crates/papyrus_protobuf/build.rs
crates/papyrus_protobuf/src/converters/event.rs
crates/papyrus_protobuf/src/converters/mod.rs
crates/papyrus_protobuf/src/proto/p2p/proto/event.proto

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2102)

feat(network): add conversion between protobuf Event and sn api

---

Cargo.lock
crates/papyrus_protobuf/Cargo.toml
crates/papyrus_protobuf/src/converters/transaction.rs
crates/papyrus_protobuf/src/converters/transaction_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2104)

test(protobuf): add transaction conversion test

---

crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2105)

fix(network): flatten output of db executor query

---

crates/papyrus_protobuf/src/converters/event.rs
crates/papyrus_protobuf/src/converters/event_test.rs
crates/papyrus_protobuf/src/converters/transaction_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2107)

test(protobuf): add test for event conversion

---

crates/papyrus_network/src/db_executor/mod.rs
crates/papyrus_network/src/db_executor/test.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2106)

fix(network): move code for adding fin from network manager to db executor

---

crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2116)

chore(protobuf): define length of statediffchunk

---

crates/papyrus_protobuf/src/converters/state_diff.rs
crates/papyrus_protobuf/src/converters/state_diff_test.rs
crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2123)

test(protobuf): add tests for state_diff conversion

---

crates/papyrus_storage/src/body/events.rs
crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/lib.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/state/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2117)

perf(storage)!: use table types and configuration changes

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_node/Cargo.toml
crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/lib.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context_test.rs
crates/sequencing/papyrus_consensus/src/test_utils.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2133)

feat: integrate consensus into main

---

crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/db/mod.rs
crates/papyrus_storage/src/mmap_file/mod.rs
crates/papyrus_storage/src/state/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2132)

docs(storage): add document for storage

---

crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/test.rs

- fix(network): peer manager finds new peers through identify instead of ConnectionEstablished
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1980)

fix(network): peer manager finds new peers through identify instead of ConnectionEstablished

---

crates/sequencing/papyrus_consensus/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2146)

docs(consensus): warn missing documentation for public members

---

crates/papyrus_protobuf/src/converters/header.rs
crates/papyrus_protobuf/src/converters/header_test.rs
crates/papyrus_protobuf/src/sync.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2129)

test(protobuf): use get_test_instance in header_test

---

crates/papyrus_sync/src/sources/central.rs
crates/papyrus_sync/src/sources/central_test.rs
crates/starknet_client/src/reader/objects/block.rs
crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2149)

fix(starknet_client): support 0.13.2 block signature format

---

Monitoring/grafana.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2144)

chore(monitoring): change default RPC version in the dashboard

---

deployments/helm/values.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2145)

chore(helm): fix default image tag

---

crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/src/header.rs
crates/papyrus_p2p_sync/src/lib.rs
crates/papyrus_p2p_sync/src/state_diff.rs
crates/papyrus_p2p_sync/src/stream_factory.rs
crates/papyrus_p2p_sync/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2147)

chore(sync): create channel struct

---

crates/sequencing/papyrus_consensus/README.md
crates/sequencing/papyrus_consensus/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2141)

feat(consensus): add README to help running milestone 1

---

crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/src/header_test.rs
crates/papyrus_p2p_sync/src/lib.rs
crates/papyrus_p2p_sync/src/state_diff_test.rs
crates/papyrus_p2p_sync/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2156)

chore(sync): add transaction channels

---

crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2152)

feat(consensus): consensus should only register with the network if it will run

---

crates/sequencing/papyrus_consensus/src/lib.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2159)

feat(consensus): create the m2 state machine skeleton, which doesn't actually handle events

---

Cargo.lock
Cargo.toml
crates/papyrus_rpc/src/v0_6/transaction.rs
crates/papyrus_rpc/src/v0_7/transaction.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/starknet_client/src/reader/objects/transaction.rs
crates/test_utils/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2142)

fix(starknet_client): add new 0.13.2 builtins

---

Cargo.lock
crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2160)

feat(consensus): add event handling to the state machine

---

crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/stream_factory.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2170)

refactor(sync): move create_stream logic to p2p_sync_channels

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2171)

refactor(network): rename register_broadcast_subscriber to register_broadcast_topic

---

crates/papyrus_p2p_sync/src/server/mod.rs
crates/papyrus_p2p_sync/src/server/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2148)

test(network): add test for Transaction and StateDiff protocols

---

crates/papyrus_protobuf/src/consensus.rs
crates/papyrus_protobuf/src/converters/consensus.rs
crates/papyrus_protobuf/src/proto/p2p/proto/consensus.proto
crates/sequencing/papyrus_consensus/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2161)

feat(consensus): add protobufs for voting

---

Cargo.lock
Cargo.toml
crates/papyrus_common/src/block_hash.rs
crates/papyrus_protobuf/src/converters/header.rs
crates/papyrus_storage/src/header.rs
crates/papyrus_storage/src/serialization/serializers.rs
crates/papyrus_storage/src/test_instances.rs
crates/starknet_client/src/reader/objects/block.rs
crates/test_utils/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2153)

fix(storage): make n_transactions and n_events non optional

---

crates/starknet_client/src/reader/objects/block.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2173)

feat(starknet_client): block may have receipt_commitment and state_diff_length

---

crates/starknet_client/src/reader/objects/test_utils.rs
crates/starknet_client/src/reader/objects/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2154)

feat(starknet_client): receive total_gas_consumed from feeder

---

crates/papyrus_p2p_sync/src/server/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2177)

test(sync): add test for Event and Class Protocol

---

config/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_storage/src/compression_utils.rs
crates/papyrus_storage/src/db/serialization.rs
crates/papyrus_storage/src/mmap_file/mod.rs
crates/papyrus_storage/src/serialization/serializers.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2179)

fix(storage): fix max object size

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2182)

refactor(network): rename register_sqmr_subscriber to protocol_client

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/sequencing/papyrus_block_builder/Cargo.toml
crates/starknet_client/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2183)

chore: bump crates version to 0.4.0-dev.4

---

config/default_config.json
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2184)

chore(network): remove header_buffer_size

---

config/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2185)

chore(sync): add buffer_size to sync config

---

crates/papyrus_node/src/config/mod.rs
crates/papyrus_node/src/config/pointers.rs
crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2186)

refactor(sync): rename p2psync to be explicit between client and server

---

crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2166)

refactor(consensus): switch StateMachine from GetProposal to StartValue

---

crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2167)

refactor(consensus): state machine returns VecDeque instead of Vec

---

.github/workflows/docker-publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2192)

chore: add tag label in docker publish GH action

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2168)

refactor(consensus): single height consensus begins using state machine without voting

---

crates/papyrus_execution/resources/versioned_constants_13_0.json
crates/papyrus_execution/resources/versioned_constants_13_1.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2196)

chore(execution): sort versioned constants

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/types.rs

I don't add tests for votes and proposals coming out of order since that is fundamentally part of
the state machine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2174)

feat(consensus): add support in SingleHeightConsensus for votes

---

crates/papyrus_sync/src/lib.rs
crates/papyrus_sync/src/sources/central.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2199)

chore: display hash as hex instead of dec

---

crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/state_machine_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2188)

feat(consensus): minor cleanups in SHC and SM

---

crates/sequencing/papyrus_consensus/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2190)

feat(consensus): update README for running milestone 2

---

crates/starknet_client/src/reader/objects/pending_data.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2203)

fix(starknet_client): fix pending block deserialization

---

config/default_config.json
crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
crates/papyrus_node/src/main.rs
crates/sequencing/papyrus_consensus/README.md
crates/sequencing/papyrus_consensus/src/config.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2194)

chore(config): add num_of_validators to ConsensusConfig

---

crates/sequencing/papyrus_consensus/run_consensus.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2198)

chore(consensus): add script for running consensus simulation

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2201)

refactor(network): change report callbacks to be a oneshot

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/bin/streamed_bytes_benchmark.rs
crates/papyrus_network/src/lib.rs
crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/sqmr/behaviour.rs
crates/papyrus_network/src/sqmr/behaviour_test.rs
crates/papyrus_network/src/sqmr/flow_test.rs
crates/papyrus_network/src/sqmr/handler.rs
crates/papyrus_network/src/sqmr/handler_test.rs
crates/papyrus_network/src/sqmr/mod.rs
crates/papyrus_network/src/sqmr/protocol.rs
crates/papyrus_network/src/sqmr/protocol_test.rs
crates/papyrus_network/src/test_utils/get_stream.rs
crates/papyrus_network/src/test_utils/mod.rs
crates/papyrus_node/src/main.rs
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_p2p_sync/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2193)

refactor(network): move Protocol to papyrus_p2p_sync

---

Cargo.lock
crates/papyrus_common/src/metrics.rs
crates/sequencing/papyrus_consensus/Cargo.toml
crates/sequencing/papyrus_consensus/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2204)

feat(consensus): add metrics to consensus

---

crates/sequencing/papyrus_consensus/src/lib.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
crates/sequencing/papyrus_consensus/src/state_machine.rs
crates/sequencing/papyrus_consensus/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2206)

feat(consensus): single height consensus returns Decision with Precommits

---

crates/papyrus_rpc/src/v0_7/api/api_impl.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2210)

chore: replace ok_or with ok_or_else

---

crates/papyrus_storage/src/body/body_test.rs
crates/papyrus_storage/src/body/mod.rs
crates/papyrus_storage/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2211)

fix(storage): update the offset of transaction and outputs files

---

crates/papyrus_p2p_sync/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2207)

refactor(network): update protocol string names

---

crates/papyrus_network/src/network_manager/swarm_trait.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_network/src/sqmr/behaviour.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2205)

chore(network): get peer_id from session_id in swarmtrait

---

crates/papyrus_network/src/mixed_behaviour.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2197)

refactor(network): gossipsub should forward messages up to 1MB

---

Cargo.lock
Cargo.toml
crates/papyrus_base_layer/Cargo.toml
crates/papyrus_execution/Cargo.toml
crates/papyrus_monitoring_gateway/Cargo.toml
crates/papyrus_network/Cargo.toml
crates/papyrus_node/Cargo.toml
crates/papyrus_node/src/version.rs
crates/papyrus_p2p_sync/Cargo.toml
crates/papyrus_rpc/Cargo.toml
crates/papyrus_storage/Cargo.toml
crates/papyrus_sync/Cargo.toml
crates/sequencing/papyrus_block_builder/Cargo.toml
crates/starknet_client/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2224)

chore: bump node and crates version

---

crates/papyrus_node/src/version.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2226)

chore: bump node version to 0.5.0 dev

---

crates/papyrus_network/src/peer_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2220)

fix(network): bugfix where the connection established event comes before PM registered the peer

---

crates/papyrus_network/src/sqmr/behaviour.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2218)

chore(network): log session assigned

---

crates/papyrus_network/src/network_manager/mod.rs
crates/papyrus_network/src/network_manager/test.rs
crates/papyrus_p2p_sync/src/client/header.rs
crates/papyrus_p2p_sync/src/client/header_test.rs
crates/papyrus_p2p_sync/src/client/mod.rs
crates/papyrus_p2p_sync/src/client/state_diff.rs
crates/papyrus_p2p_sync/src/client/state_diff_test.rs
crates/papyrus_p2p_sync/src/client/stream_builder.rs
crates/papyrus_p2p_sync/src/client/test_utils.rs
crates/sequencing/papyrus_consensus/src/lib.rs
crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2213)

refactor(network): move callback from response_receiver to query_sender

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2229)

feat(network): add structs for new Sqmr interface

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2232)

feat(network): add implementation from SqmrClientPayload to SqmrClientPayloadForNetwork

---

crates/sequencing/papyrus_consensus/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2236)

fix(consensus): resolve dropped messages

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2244)

fix(network): remove TryFrom for response from server payload

---

Cargo.lock
crates/papyrus_network/Cargo.toml
crates/papyrus_network/src/peer_manager/behaviour_impl.rs
crates/papyrus_network/src/peer_manager/mod.rs
crates/papyrus_network/src/peer_manager/peer.rs
crates/papyrus_network/src/peer_manager/test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2222)

fix(network): if all peers are blocked, act as if there are no peers

---

crates/papyrus_network/src/network_manager/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2245)

feat(network): impl From<SqmrServerPayloadForNetwork> for SqmrServerPayload
