- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/serializers_test.rs
- crates/papyrus_storage/src/test_utils.rs
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/415)
> Add a seed to get_test_instance

- README.md
Issue Number: Fixes #451 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/453)
> Fix license in readme

- crates/papyrus_load_test/Cargo.toml
- crates/papyrus_load_test/src/main.rs
Optionally output load test results in [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark) compatible format.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/456)
> Dump load test results

- config/config.yaml
- crates/papyrus_node/src/bin/starknet_client_integration_test.rs
- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/file_config.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/starknet_client/Cargo.toml
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/starknet_client_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/404)
> Add throttling bypass.

- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/state/state_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/457)
> Test storage readers functions after reverts (additional checks)

- config/config.yaml
- crates/papyrus_node/src/config/file_config.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/462)
> Remove nanos from sync config.

- crates/papyrus_sync/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/463)
> Remove unnecessary code

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/464)
> Fix contract address in deploy account receipt

- crates/papyrus_sync/src/sources/central.rs
- crates/starknet_client/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/467)
> Fix log levels

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/objects/block.rs
BlockNumber and BlockHash are printed with Debug format
BlockNumber and BlockHash are printed with Display format
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/469)
> Use Display of BlockNumber and BlockHash instead of Debug

- crates/papyrus_sync/src/sources/central.rs
Needed in order to provide better tracing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/472)
> Extract to functions transforming of client data to central data

- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/ommer/mod.rs
- crates/papyrus_storage/src/ommer/ommer_test.rs
- crates/papyrus_storage/src/state/data.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/central_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/473)
> Pass classes to storage in IndexMap and don't clone them.

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_sync/src/lib.rs
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/starknet_client_test.rs
- crates/test_utils/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/478)
> Fix clippy

- crates/papyrus_node/Cargo.toml
- crates/papyrus_node/src/config/config_test.rs
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/471)
> Add set_workspace_root function.

- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
Fix logs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/481)
> Move logging of large data to level trace instead of debug

- crates/papyrus_load_test/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/474)
> Style changes in load_test.

- config/config.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/466)
> Add explanation to the config file.

- crates/papyrus_monitoring_gateway/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/483)
> Tracing: open span for monitoring gateway callbacks

- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/body/mod.rs
When reverting a block, the events are not deleted (though they remain unreachable).
The events are deleted.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/485)
> Fix bug in reverts (not deleting the events)

- crates/papyrus_sync/src/sources/central_sync_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/493)
> Make it possible to set log level in tests

- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/495)
> Add debug logs to the sync

- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/498)
> Change stream to try_stream in sync

- crates/papyrus_load_test/src/gateway_endpoints.rs
- crates/papyrus_load_test/src/lib.rs
- crates/papyrus_load_test/src/load_tests.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/490)
> Remove unnecessary use of generic.

- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_sync/Cargo.toml
- crates/starknet_client/Cargo.toml
- crates/test_utils/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/512)
> Bump version starknetAPI.

- Dockerfile
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/514)
> Bump rust version

- .dockerignore
- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/522)
> add load test resources to docker image

- crates/papyrus_load_test/src/create_request.rs
- crates/papyrus_load_test/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/524)
> Fix create request for get block by number.

- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/body/events.rs
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/header.rs
- crates/papyrus_storage/src/header_test.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/ommer/mod.rs
- crates/papyrus_storage/src/ommer/ommer_test.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/521)
> Return deleted data from revert and don't fail on an invalid revert.

- crates/papyrus_node/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/529)
> Disable base layer dependency

- crates/papyrus_load_test/src/scenarios.rs
- crates/papyrus_load_test/src/transactions.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/518)
> Add constant gateway requests to the load test.

- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/538)
> Add option to config the central url using command line.

- crates/starknet_client/resources/block_state_update.json
- crates/starknet_client/src/objects/block_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/539)
> Add declared contract to the client test

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/state.rs
- crates/papyrus_gateway/src/transaction.rs
- crates/starknet_client/src/objects/block.rs
- crates/starknet_client/src/objects/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/546)
> Clippy upgrade fix.

- .github/workflows/helm-install.yml
- deployments/helm/CI/values.yaml
- deployments/helm/backup-values.yaml
- deployments/helm/files/backup.sh
- deployments/helm/templates/aws-creds-secret.yaml
- deployments/helm/templates/configmap.yaml
- deployments/helm/templates/deployment.yaml
- deployments/helm/templates/pvc.yaml
- deployments/helm/templates/run-configmap.yaml
- deployments/helm/templates/svc.yaml
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/547)
> Support periodic backups to S3

- crates/papyrus_storage/src/ommer/ommer_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/549)
> Remove unnecessary tests

- docs/CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/544)
> add readme describing how to setup the environment

- crates/papyrus_node/Cargo.toml
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_node/src/lib.rs
- crates/papyrus_node/src/version.rs
- crates/papyrus_node/src/version_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/552)
> Add version

- crates/papyrus_monitoring_gateway/src/gateway_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/560)
> Fix monitoring GW tests.

- crates/papyrus_load_test/src/create_files.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/559)
> Make create_files using async tasks.

- deployments/helm/files/backup.sh
- deployments/helm/templates/aws-creds-secret.yaml
- deployments/helm/templates/configmap.yaml
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/566)
> backup - add support for setting number of concurrent feeder-gw requests

- config/config.yaml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/db/serialization.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/serializers_test.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_sync/Cargo.toml
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
Serialization endianness is not deterministic. This leads to wrong DB keys comparison.
Fixed big-endiannes. 
-
New DB schema may not be backward compatible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/568)
> Fix storage endianness

- crates/papyrus_base_layer/Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/resources/starknet_api_openrpc.json
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_sync/Cargo.toml
- crates/starknet_client/Cargo.toml
- crates/starknet_client/src/objects/transaction.rs
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/572)
> Bump SN_API version

- crates/papyrus_load_test/src/create_request.rs
- crates/papyrus_load_test/src/scenarios.rs
- crates/papyrus_load_test/src/transactions.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/551)
> Load test add transaction with only block id.

- crates/papyrus_node/src/config/file_config.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/test_utils.rs
- Matches `mdbx`'s representation of this type as a `PathBuf`.
- Simplifies path logic.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/575)
> Change `Db[Config].path` type from "String" to `PathBuf`

- crates/papyrus_base_layer/Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/resources/starknet_api_openrpc.json
- crates/papyrus_gateway/src/transaction.rs
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_sync/Cargo.toml
- crates/starknet_client/Cargo.toml
- crates/starknet_client/resources/block.json
- crates/starknet_client/resources/invoke_transaction.json
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/objects/block.rs
- crates/starknet_client/src/objects/block_test.rs
- crates/starknet_client/src/objects/transaction.rs
- crates/starknet_client/src/objects/transaction_test.rs
- crates/starknet_client/src/starknet_client_test.rs
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/561)
> Declare V2

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/558)
> Add README explanation on how to limit the memory usage of the node

- crates/papyrus_base_layer/Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_sync/Cargo.toml
- crates/starknet_client/Cargo.toml
- crates/test_utils/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/583)
> Bump SN API to `1e2f66c`.

- crates/papyrus_storage/src/state/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/587)
> Delete replaced classes when reverting

- crates/papyrus_base_layer/Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_sync/Cargo.toml
- crates/starknet_client/Cargo.toml
- crates/test_utils/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/598)
> Update starknet-api (added Copy)

- deployments/helm/CI/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/590)
> helm chart: add a commented example for ingress usage

- crates/papyrus_storage/src/state/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/597)
> Add documentation to the structure of state data.

- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_node/src/bin/starknet_client_integration_test.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_node/src/main.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/starknet_client_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/576)
> Add version to the client.

- crates/papyrus_gateway/src/gateway_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/604)
> Add new class scenarios to the old get_class_at test in the gateway.

- crates/papyrus_storage/src/state/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/605)
> Delete unnecessary if in delete_declared_classes function.

- crates/papyrus_node/src/bin/starknet_client_integration_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/606)
> Changes in client integration tets.

- crates/papyrus_storage/src/state/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/613)
> Delete duplicate check in delete_deprecated_declare_classes function.

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/data.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/test_utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/615)
> Rename storage indexed contract class

- crates/papyrus_sync/src/sources/central_test.rs
- crates/starknet_client/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/616)
> Test streaming replaced classes

- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/objects/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/617)
> Add informative data to BadTransaction error

- crates/starknet_client/src/objects/state.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/618)
> StateDiff serialization/deserialization

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/643)
> Add merge group support to CI

- .github/workflows/ci.yml
- Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_load_test/Cargo.toml
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_sync/Cargo.toml
- crates/starknet_client/Cargo.toml
- crates/test_utils/Cargo.toml
Removes duplication in versions across crates.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/602)
> Move all dependencies to the workspace `Cargo.toml` + alphabetize

- config/config.yaml
- crates/papyrus_node/src/config/file_config.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/640)
> Limit stream size

- crates/starknet_client/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/642)
> Remove todo

- deployments/helm/CI/values.yaml
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/645)
> helm - use mainnet in ci

- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/test_utils.rs
- crates/papyrus_storage/src/version.rs
- crates/papyrus_storage/src/version_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/646)
> Add storage version check

- crates/papyrus_node/src/version.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/648)
> Bump version

- deployments/helm/templates/deployment.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/651)
> Pass central url and chain ID CLA to helm deployment

- Cargo.toml
- crates/papyrus_base_layer/Cargo.toml
- crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
- crates/papyrus_node/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/619)
> Upgrade ethers

- crates/test_utils/src/lib.rs
**Stack**:
- #639
- #638
- #637
- #636
- #635
- #634
- #633
- #632
- #631
- #630 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/630)
> test utils file restructuring - no functional diff

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/serializers_test.rs
- crates/test_utils/src/lib.rs
**Stack**:
- #639
- #638
- #637
- #636
- #635
- #634
- #633
- #632
- #631 ⬅
- #630
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/631)
> shift to using get_rng for random gen

- crates/test_utils/src/lib.rs
**Stack**:
- #639
- #638
- #637
- #636
- #635
- #634
- #633 ⬅
- #632
- #631
- #630
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/633)
> remove unused function - get_rand_test_body

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/body/body_test.rs
- crates/test_utils/src/lib.rs
commit-id:1499ca6d
---
**Stack**:
- #639
- #638
- #637
- #636
- #635
- #634 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/634)
> consolidate get_test_body_with_events and get_test_body

- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/655)
> Update SN API dependency revision.

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/ommer/ommer_test.rs
- crates/test_utils/src/lib.rs
commit-id:e2d76ef4
---
**Stack**:
- #639
- #638
- #637
- #636
- #635 ⬅
- #634
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/635)
> consolidate get_test_block_with_events and get_test_block

- crates/papyrus_monitoring_gateway/src/gateway_test.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/656)
> Prefix monitoring endpoints

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/body/body_test.rs
- crates/test_utils/src/lib.rs
commit-id:30c1cdb7
---
**Stack**:
- #639
- #638
- #637
- #636 ⬅
- #635
- #634
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/636)
> make get_rand_test_body_with_events private

- Cargo.toml
- crates/starknet_client/Cargo.toml
- crates/starknet_client/resources/casm_contract_class.json
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/starknet_client_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/658)
> Add casm_contract_class to SN client

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/ommer/ommer_test.rs
- crates/test_utils/src/lib.rs
commit-id:e8238dd7
---
**Stack**:
- #639
- #638
- #637 ⬅
- #636
- #635
- #634
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/637)
> make get_rand_test_block_with_events private

- crates/papyrus_gateway/src/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/650)
> Fix bug in deserializing declare tx in the gateway

- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/664)
> Change starknet_api revision to latest revision.

- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/data.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_storage/src/test_utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/668)
> declare class table split

- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/675)
> fix cairo lang version

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/transaction.rs
…g from reapearing
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/665)
> bugfix - Transactions deserialization

- Cargo.toml
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/677)
> Dan/bump version/cairo

- deployments/helm/files/backup.sh
- deployments/helm/templates/configmap.yaml
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/673)
> backup mode: give the ability to compress the backups

- crates/papyrus_node/src/main.rs
- crates/papyrus_storage/src/body/events.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/state/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/669)
> Refactor some if let statements

- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/state/state_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/674)
> add class deff block num api

- crates/papyrus_storage/src/state/state_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/683)
> Change assert_matches! to assert! in append_state_diff_declared_classes.

- Cargo.toml
- crates/papyrus_gateway/src/api/mod.rs
- crates/papyrus_gateway/src/api/v0_3_0/mod.rs
- crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_impl.rs
- crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/667)
> upgrade jsonrpsee version to add support for middleware

- Cargo.toml
- crates/papyrus_execution/Cargo.toml
- crates/papyrus_execution/resources/compiled_class.json
- crates/papyrus_execution/src/blockifier_state.rs
- crates/papyrus_execution/src/blockifier_state_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/compiled_class_test.rs
Introducing an execution crate, implementing the the blockifier state reader API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/685)
> Add execution crate with blockifier state implementation

- crates/papyrus_execution/Cargo.toml
- crates/papyrus_execution/src/blockifier_state.rs
- crates/papyrus_execution/src/blockifier_state_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/690)
> Refactor blcokifier state trait implementation

- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/687)
> In case of a bad URL warn instead of error.

- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/693)
> Bump blockifier version main-v0.12.0

- crates/papyrus_storage/src/state/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/688)
> documentation and improvements to StateReader

- crates/papyrus_sync/Cargo.toml
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/central_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/670)
> Stream compiled classes (Cairo 1 Casm)

- Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/api/mod.rs
- crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs
- crates/papyrus_gateway/src/api/version_config.rs
- crates/papyrus_gateway/src/api/version_config_test.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/middleware.rs
- crates/papyrus_monitoring_gateway/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/671)
> add middleware

- Cargo.toml
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/698)
> jsonrpsee version upgrade

- crates/papyrus_gateway/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/699)
> add max body size

- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_storage/src/test_utils.rs
- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/694)
> Sync compiled classes

- crates/papyrus_monitoring_gateway/src/gateway_test.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/697)
> Add liveness endpoint to the monitoring gateway.

- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/middleware.rs
- crates/papyrus_gateway/src/test_utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/703)
> use version in server

- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/src/gateway_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/710)
> Request app using special function; In monitoring gw test.

- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/gateway_metrics/gateway_metrics_test.rs
- crates/papyrus_gateway/src/gateway_metrics/mod.rs
- crates/papyrus_gateway/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/717)
> Collect metrics in the gateway.

- Cargo.toml
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/src/gateway_test.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/712)
> Collect metrics in the monitoring gateway.

- crates/starknet_client/src/lib.rs
Use default value for CasmConractClass that are malformed in the integration environment.
Feeder returns malformed CasmConractClass for few class hashes.
Instead of downloading from the feeder, use the default value.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/726)
> Dan/sn client/integration

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/727)
> Try to fix codecov 404 error code.

- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/compiled_class_test.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/724)
> Borrow instead of copy

- Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/deprecated_contract_class.rs
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/starknet_client/src/objects/deprecated_contract_class.rs
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/731)
> Update starknet_api and cairo-lang dependencies.

- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/743)
> Update SN API revision.

- Cargo.toml
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/serializers.rs
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/691)
> Storage serde for casms

- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/748)
> Update SN API commit.

- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/src/gateway_test.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/719)
> Add process metrics (memory and cpu usage).

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/data.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_storage/src/test_utils.rs
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/747)
> Unify storage tables of deployed contracts and replaced classes

- crates/papyrus_storage/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/752)
> Bump storage version from 0 to 1

- crates/test_utils/src/lib.rs
- [] Documentation content changes
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/751)
> Delete a todo.

- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/746)
> refactor Cargo.toml

- Cargo.lock
- crates/papyrus_config/Cargo.toml
- crates/papyrus_config/src/lib.rs
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
- crates/papyrus_node/Cargo.toml
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
- The default values for the configs are set centrally in the node crate.
- Implement Default for each config component individually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/718)
> Implement Default for each config component individually.

- crates/papyrus_storage/src/body/events.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/759)
> Add documentation for papyrus_storage::body::events.

- Cargo.lock
- config/default_config.json
- crates/papyrus_config/Cargo.toml
- crates/papyrus_config/src/config_test.rs
- crates/papyrus_config/src/lib.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/snapshots/papyrus_gateway__gateway_test__dump_default_config.snap
- Loading the dump file for configurations to config objects.
- Currently only for the gateway config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/755)
> Add load trait for sub configs.

- deployments/helm/CI/values.yaml
- deployments/helm/backup-values.yaml
- deployments/helm/templates/deployment.yaml
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/765)
> helm: align image tag, conditional ports

- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/starknet_client_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/779)
> Use blockNumber=latest in queries to the feeder gateway

- crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_monitoring_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/compiled_class_test.rs
- crates/papyrus_storage/src/db/db_test.rs
- crates/papyrus_storage/src/header_test.rs
- crates/papyrus_storage/src/ommer/ommer_test.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_storage/src/test_utils.rs
- crates/papyrus_storage/src/version_test.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/central_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/766)
> return temp dir from test storage creation

- Cargo.lock
- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/784)
> Bump starknetAPI version.

- crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_impl.rs
- crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/transaction.rs
- crates/papyrus_storage/src/base_layer.rs
- crates/papyrus_storage/src/base_layer_test.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/785)
> Add base layer status in the storage and gateway.

- Cargo.lock
- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/786)
> Use SN API crate from crates.io

- Cargo.lock
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/gateway_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/767)
> add test for ContractClassAbiEntryWithType from ontractClassAbiEntry

- crates/papyrus_gateway/src/gateway_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/773)
> add test from_transaction_output

- crates/starknet_client/src/objects/transaction.rs
- crates/starknet_client/src/objects/transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/792)
> deny unkown fields in txs of sn client

- crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/transaction.rs
- crates/papyrus_storage/src/base_layer.rs
- crates/papyrus_storage/src/base_layer_test.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/787)
> CR fix for.

- crates/papyrus_gateway/src/gateway_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/772)
> add test for ContractClassAbiEntryType from FunctionAbiEntryType

- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/transaction_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/774)
> add test from_thin_transaction_output

- config/config.yaml
- crates/papyrus_node/src/config/file_config.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/test_utils.rs
The DB config has the param: `path`.
During the config generation, the path comprises two parts - the prefix and the chain ID.
- Splitting the `path` in DB config into two parts: path prefix and chain id.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/797)
> Add chain id to db config.

- crates/starknet_client/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/803)
> Support new SN error code

- Cargo.lock
- Cargo.toml
- crates/starknet_client/src/lib.rs
- crates/starknet_writer_client/Cargo.toml
- crates/starknet_writer_client/src/lib.rs
- crates/starknet_writer_client/src/objects/mod.rs
- crates/starknet_writer_client/src/objects/transaction.rs
- crates/starknet_writer_client/src/objects/transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/798)
> add DeployAccountTransaction to SN writer client

- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/central_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/761)
> Separate block headers and body sync

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/771)
> make CI run on PRs into branches other than main

- crates/papyrus_sync/src/sources/central_sync_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/810)
> Higher test sync time

- crates/papyrus_node/src/version.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/809)
> Bump version to 0.1.3-stable

- crates/papyrus_node/src/version.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/811)
> Bump version to 0.1.4-dev

- deployments/helm/CI/values.yaml
- deployments/helm/backup-values.yaml
- deployments/helm/templates/aws-creds-secret.yaml
- deployments/helm/templates/configmap.yaml
- deployments/helm/templates/deployment.yaml
- deployments/helm/values.yaml
- values.yaml `image` section is now nested under `deployment`
- all yaml keys are now in camelCase
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/802)
> helm chart improvements

- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/central_test.rs
This reverts commit bc645cca84c992835311c22684847ab807f2c354.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/813)
> Revert "Separate block headers and body sync (#761)"

- crates/starknet_writer_client/src/objects/transaction.rs
- crates/starknet_writer_client/src/objects/transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/806)
> add the rest of the transactions to the writer client

- .github/ISSUE_TEMPLATE/config.yml
Fix link in issues template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/816)
> Update issue_template config.yml with right discussions link

- crates/papyrus_sync/src/sources/central_sync_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/823)
> Fix duration initialization

- crates/papyrus_storage/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/818)
> Make markers public only in the storage crate

- crates/papyrus_storage/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/819)
> Make table identifiers public only in the storage crate

- crates/papyrus_storage/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/820)
> Documentation for the storage lib file

- crates/papyrus_monitoring_gateway/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/828)
> Fix monitoring/alive API

- crates/papyrus_gateway/src/transaction_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/775)
> add test gateway_trascation_from_starknet_api_transaction

- crates/papyrus_gateway/src/transaction_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/776)
> add transaction hash test to the transaction conversion test

- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/781)
> add tests for erro flow in sync

- crates/papyrus_storage/src/body/events.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/header.rs
- crates/papyrus_storage/src/state/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/835)
> Documentation for header, body and state modules of the storage crate

- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/header_test.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_storage/src/version_test.rs
- crates/papyrus_sync/src/sources/central_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/842)
> Change if let to let else

- crates/papyrus_storage/src/compiled_class.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/838)
> Documentation for compiled classes the storage

- crates/papyrus_storage/src/base_layer.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/839)
> Documentation for the base layer in the storage

- crates/papyrus_storage/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/847)
> Add disclaimer for expected breaking changes in the storage

- Cargo.toml
- crates/papyrus_config/src/command.rs
- crates/papyrus_config/src/config_test.rs
- Update the config map by environment variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/853)
> Update config map by env vars.

- Cargo.lock
- Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/resources/starknet_api_openrpc.json
- crates/papyrus_gateway/src/broadcasted_transaction.rs
- crates/papyrus_gateway/src/broadcasted_transaction_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_storage/src/test_utils.rs
- crates/starknet_writer_client/Cargo.toml
- crates/starknet_writer_client/src/lib.rs
- crates/starknet_writer_client/src/objects/mod.rs
- crates/starknet_writer_client/src/objects/test_utils.rs
- crates/starknet_writer_client/src/objects/transaction.rs
- crates/test_utils/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/824)
> Add broadcasted tx struct with openrpc tests

- Cargo.lock
- Cargo.toml
- crates/starknet_reader_client/Cargo.toml
- crates/starknet_reader_client/src/objects/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/851)
> Use lazy_static consts instead of calling functions

- crates/papyrus_storage/src/body/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/844)
> Remove stale comment

- Cargo.lock
- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/861)
> Set initial workspace package version

- crates/papyrus_storage/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/864)
> Fix documentation typo

- crates/starknet_writer_client/src/objects/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/855)
> doc transactions of SN writer client

- crates/starknet_reader_client/src/lib.rs
- crates/starknet_writer_client/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/856)
> add doc to SN reader and writer clients

- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_sync/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/865)
> Add crates io dependencies for papyrus_storage

- crates/papyrus_gateway/src/broadcasted_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/860)
> add doc to broadcasted txs

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class_test.rs
- crates/papyrus_gateway/src/v0_3_0/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/845)
> move contract class tests to its one file

- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/v0_3_0/api/mod.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class_test.rs
- crates/papyrus_gateway/src/v0_3_0/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/846)
> move event chunk and gatway contract class structs to version folder

- config/config.yaml
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_node/src/config/file_config.rs
- crates/papyrus_node/src/config/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/866)
> Set logger in the gateway by collect_metrics flag

- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/block.rs
- crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class_test.rs
- crates/papyrus_gateway/src/v0_3_0/transaction_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/850)
> use super for version imports

- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_node/src/bin/dump_config.rs
- crates/papyrus_node/src/bin/starknet_client_integration_test.rs
- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/886)
> Rename the config of the node crate to NodeConfig.

- crates/papyrus_gateway/src/v0_3_0/deprecated_contract_class.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/875)
> prepare v0.3.0 for v0.4.0 addition

- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/880)
> rename into rpc method

- Cargo.lock
- Cargo.toml
- crates/papyrus_gateway/src/broadcasted_transaction_test.rs
- crates/papyrus_storage/src/body/body_test.rs
- crates/starknet_reader_client/src/objects/block.rs
- crates/starknet_writer_client/resources/declare_v1.json
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/879)
> starknet api version change

- Cargo.lock
- crates/starknet_writer_client/Cargo.toml
- crates/starknet_writer_client/resources/declare_response.json
- crates/starknet_writer_client/resources/deploy_account_response.json
- crates/starknet_writer_client/resources/invoke_response.json
- crates/starknet_writer_client/src/objects/mod.rs
- crates/starknet_writer_client/src/objects/response.rs
- crates/starknet_writer_client/src/objects/response_test.rs
- crates/starknet_writer_client/src/objects/transaction_test.rs
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/862)
> add SN writer client responses

- .github/workflows/ci.yml
- check_starknet_api_version_dependency.sh
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/868)
> check starknet_api dependency

- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/894)
> Exit gracefully when --help or --version are used

- crates/starknet_reader_client/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/896)
> move common client functionality to StarknetBaseClient

- Cargo.lock
- Cargo.toml
- crates/papyrus_gateway/src/transaction.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/api/mod.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_3_0/transaction.rs
- crates/papyrus_gateway/src/v0_3_0/transaction_test.rs
- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_sync/src/lib.rs
- crates/starknet_reader_client/src/objects/block.rs
- crates/starknet_reader_client/src/objects/transaction.rs
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/895)
> Bump starknet api version, location of transaction hash.

- Cargo.lock
- Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/903)
> chore(release): bump starknet_api version to 0.3.0

- Cargo.lock
- Cargo.toml
- crates/papyrus_config/Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_sync/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/904)
> chore(release): bump workspace version to 0.0.2

- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_3_0/transaction_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/917)
> style(gateway): v3 minor fixes to match v4 and improve styling

- .github/workflows/ci.yml
- commitlint.config.js
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/911)
> ci: add commitlint

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/middleware.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/920)
> feat(gateway): support lowercase v in rpc path (i.e /rpc/v0_3_0 and /rpc/V0_3_0)

- Cargo.lock
- crates/papyrus_config/src/command.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/921)
> Remove arg! macro.

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/918)
> ci: fix starkent api dependency check

- crates/papyrus_gateway/resources/V0_4_0_starknet_api_openrpc.json
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/block.rs
- crates/papyrus_gateway/src/v0_4_0/deprecated_contract_class.rs
- crates/papyrus_gateway/src/v0_4_0/deprecated_contract_class_test.rs
- crates/papyrus_gateway/src/v0_4_0/mod.rs
- crates/papyrus_gateway/src/v0_4_0/state.rs
- crates/papyrus_gateway/src/v0_4_0/transaction.rs
- crates/papyrus_gateway/src/v0_4_0/transaction_test.rs
- crates/papyrus_gateway/src/version_config.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/877)
> add v0.4.0 not connected to endpoint

- .gitignore
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/925)
> chore: ignore husky git hooks

- crates/starknet_client/Cargo.toml
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/reader/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/926)
> doc(starknet_client): fix doc and crate description.

- crates/papyrus_gateway/resources/V0_3_0_starknet_api_openrpc.json
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/899)
> fix(gateway): v3 rejectedb locks and reverted tx handle

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/middleware.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/892)
> improve middleware tests

- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/writer/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/930)
> docs(starknet_client): fix reader and writer module docs

- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central/state_update_stream.rs
- crates/papyrus_sync/src/sources/central_test.rs
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/reader/objects/block.rs
- crates/starknet_client/src/reader/objects/block_test.rs
- crates/starknet_client/src/reader/objects/transaction.rs
- crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs
- crates/starknet_client/src/writer/mod.rs
- crates/starknet_client/src/writer/starknet_gateway_client_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/934)
> refactor(starknet_client): split error into ClientError and ReaderClientError

- .github/workflows/helm-install.yml
- commitlint.config.js
- deployments/helm/Chart.yaml
- deployments/helm/templates/deployment.yaml
prometheus doesn't scrape the metrics from the papyrus pod(s)
prometheus scrapes the metrics from the papyrus pod(s)
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/931)
> fix(helm): add prometheus scrape annotations to papyrus pod(s)

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/942)
> ci: change commitlint "from" to base sha instead of relative to "head" with number of commits

- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/writer/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/936)
> fix(starknet_client): add instrument to writer client methods

- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/reader/error.rs
- crates/starknet_client/src/reader/error_test.rs
- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/starknet_error.rs
- crates/starknet_client/src/starknet_error_test.rs
- feat(starknet_client): move code
- feat(starknet_client): add StarknetErrorCode variants and ReaderStarknetErrorCode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/945)
> shahak/sn client/more starknet error codes

- crates/papyrus_gateway/src/v0_3_0/transaction.rs
- crates/papyrus_gateway/src/v0_4_0/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/947)
> fix(JSON-RPC): fix declare v1 convertion typo

- crates/papyrus_gateway/src/v0_3_0/transaction.rs
- crates/papyrus_gateway/src/v0_4_0/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/952)
> fix(JSON-RPC): fix declare v0&v1 serde bug by failing deserialization for declare v0 is version!=0x0

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/939)
> chore: bump udeps version

- config/default_config.json
- crates/papyrus_node/src/bin/dump_config.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/937)
> Couple collect metrics flags

- crates/papyrus_gateway/resources/V0_4_0_starknet_api_openrpc.json
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/881)
> connect v0.4.0 to api endpoint

- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs
- crates/starknet_client/src/starknet_client_test.rs
- crates/starknet_client/src/test_utils/retry.rs
- test(starknet_client): move code
- test(starknet_client): change retry test to work on starknet client
- test(starknet_client): add more tests for StarknetClient
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/955)
> shahak/sn client/test base client

- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/mod.rs
- crates/papyrus_sync/src/sync_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/954)
> refactor(sync): move unitest for sync to sync_test.rs

- crates/starknet_client/src/reader/objects/block.rs
- crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs
…alization (without prefix).
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/906)
> test(reader client): make global root serialization the same as deserialization

- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_3_0/broadcasted_transaction_test.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- test(JSON-RPC): move code
- test(JSON-RPC): add function for getting a schema of a method's result
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/962)
> shahak/json rpc/get schema for method results

- Cargo.lock
- crates/papyrus_gateway/src/api.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/960)
> feat(JSON-RPC): add rpc server generator to reduce code duplication

- crates/papyrus_gateway/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/973)
> test(JSON-RPC): add function for getting a schema of a method's errors

- crates/papyrus_gateway/src/v0_4_0/mod.rs
- crates/papyrus_gateway/src/v0_4_0/write_api_error.rs
- crates/papyrus_gateway/src/v0_4_0/write_api_error_test.rs
- test(JSON-RPC): add function for getting a schema of a method's errors
- feat(JSON-RPC): add AddTransactionError
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/975)
> shahak/json rpc/add transaction error

- Cargo.lock
- config/default_config.json
- crates/papyrus_config/Cargo.toml
- crates/papyrus_config/src/config_test.rs
- crates/papyrus_config/src/dumping.rs
- crates/papyrus_config/src/lib.rs
- crates/papyrus_config/src/loading.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- Supports optional params and sub-configs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/908)
> Support optional config params.

- crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction.rs
- crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs
- crates/papyrus_gateway/src/v0_4_0/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/981)
> feat(JSON-RPC): broadcasted declare tx

- README.md
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/965)
> docs(config): update the config section in the readme

- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/979)
> chore(sync): better debug logs

- crates/papyrus_node/src/main.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/base_layer.rs
- crates/papyrus_sync/src/sources/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/968)
> feat(): error message if Ethereum node URL wasn't supplied

- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/978)
> fix(): delete todo macros

- crates/papyrus_common/src/lib.rs
- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/central_test.rs
- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs
- crates/starknet_client/tests/integration_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/983)
> feat(reader client): get the latest block

- crates/papyrus_gateway/src/v0_4_0/write_api_result.rs
- crates/papyrus_gateway/src/v0_4_0/write_api_result_test.rs
- crates/starknet_client/src/writer/objects/response.rs
- feat(JSON-RPC): add transaction ok result structs
- feat(JSON-RPC): add conversion from response to AddOkResult
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/974)
> shahak/json rpc/add ok result from response

- crates/papyrus_gateway/src/api.rs
- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/987)
> fix(config): use relative default config

- Cargo.lock
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/starknet_client_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/963)
> feat(starknet_client): retry upon StarknetErrorCode.TRANSACTION_LIMIT_EXCEEDED

- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_3_0/broadcasted_transaction_test.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/990)
> test(JSON-RPC): change get_starknet_spec_api_schema_for_components to be non async

- config/default_config.json
- crates/papyrus_config/src/lib.rs
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main.rs
- crates/starknet_client/src/writer/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/984)
> feat(JSON-RPC)!: add StarknetWriter as a member of JsonRpcServerV0_4Impl

- crates/papyrus_gateway/src/v0_4_0/write_api_error.rs
- crates/papyrus_gateway/src/v0_4_0/write_api_error_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/989)
> feat(JSON-RPC): add conversion from StarknetError to AddTransactionError

- crates/papyrus_gateway/src/lib.rs
- crates/starknet_client/src/writer/mod.rs
- crates/starknet_client/src/writer/starknet_gateway_client_test.rs
- feat(JSON-RPC)!: add StarknetWriter as a member of JsonRpcServerV0_4Impl
- feat(JSON-RPC): change gateway.starknet_gateway_retry_config description
- feat(starknet_client)!: remove http_headers from StarknetGatewayClient::new
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/991)
> shahak/starknet client/remove http headers from writer client

- crates/papyrus_gateway/src/v0_4_0/transaction.rs
- crates/papyrus_gateway/src/v0_4_0/transaction_test.rs
- crates/starknet_client/src/writer/objects/transaction.rs
- crates/starknet_client/src/writer/objects/transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/994)
> feat(JSON-RPC): add conversion to client txs for all non-declare txs

- .github/workflows/helm-install.yml
- deployments/helm/CI/values.yaml
- deployments/helm/templates/deployment.yaml
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/980)
> fix(helm): remove rewrite-target in ingress

- Cargo.lock
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/993)
> fix: kill node on sync failure

- crates/papyrus_common/src/lib.rs
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/syncing_state.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/api/mod.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/papyrus_node/src/main.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sync_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/986)
> refactor(sync): share highest block sync and gateway

- crates/papyrus_base_layer/Cargo.toml
- crates/papyrus_execution/Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_node/Cargo.toml
- crates/papyrus_sync/Cargo.toml
- crates/starknet_client/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/997)
> chore: add crates.io dependecies for published crates

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/block.rs
- crates/papyrus_gateway/src/v0_4_0/error.rs
- crates/papyrus_gateway/src/v0_4_0/transaction.rs
- refactor(JSON-RPC): move code around
- refactor(JSON-RPC): split JsonRpcError for each error
- feat(JSON-RPC): add more errors for 0.4.0 JsonRpcError
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1003)
> shahak/json rpc/add v0 4 0 errors

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1013)
> ci: commitlint PR title

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1015)
> fix: fix PR title commitlint in CI

- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1005)
> test(JSON-RPC): change validate_schema to accept objects without result field

- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1014)
> test(JSON-RPC): change get_test_rpc_server_and_storage_writer to get the mock instead of creating it

- Cargo.lock
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/syncing_state.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/api/mod.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/995)
> feat(JSON-RPC): return syncing state

- deployments/helm/templates/deployment.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1017)
> fix(helm): fix config in helm deployment

- crates/papyrus_gateway/src/v0_4_0/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1018)
> feat(JSON-RPC): add type alias for DeployAccountTransaction

- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1020)
> refactor(JSON-RPC): rpc server test util takes shared highest block

- crates/papyrus_gateway/src/v0_3_0/broadcasted_transaction_test.rs
- crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction.rs
- crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs
- crates/starknet_client/src/writer/objects/test_utils.rs
- crates/starknet_client/src/writer/objects/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1023)
> feat(starknet_client): change DeprecatedContractClass to use abi from starknet_api

- crates/papyrus_gateway/src/v0_3_0/api/mod.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1024)
> fix(JSON-RPC): omit None continuation_token in serialization

- crates/papyrus_node/src/version.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1025)
> chore(release): bump version v0.0.5

- crates/papyrus_node/src/version.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1026)
> chore(release): bump version v0.0.6-dev

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1027)
> ci: don't run commitlint on merge_group events

- crates/papyrus_gateway/src/v0_3_0/broadcasted_transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/992)
> test(JSON-RPC): add TODO to reenable broadcasted declare v1 test

- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/starknet_client/src/writer/objects/test_utils.rs
- feat(JSON-RPC): add type alias for DeployAccountTransaction
- feat(JSON-RPC): add starknet_addInvokeTransaction
- feat(JSON-RPC): add starknet_addInvokeTransaction
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1021)
> feat(JSON-RPC): add starknet_addDeployAccountTransaction

- crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction.rs
- crates/papyrus_gateway/src/v0_4_0/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1032)
> feat(JSON-RPC): add conversion from broadcasted declare to writer client declare

- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs
- crates/starknet_client/src/writer/objects/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1033)
> feat(JSON-RPC): add addDeclareTransaction

- crates/papyrus_execution/resources/erc20_fee_contract_class.json
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/objects.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1007)
> feat(execution): simulate transactions functionality

- Cargo.lock
- crates/papyrus_common/src/lib.rs
- crates/papyrus_common/src/metrics.rs
- crates/papyrus_sync/Cargo.toml
- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1039)
> chore(monitoring,sync): emit sync-related metrics

- config/default_config.json
- crates/papyrus_monitoring_gateway/src/lib.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1037)
> docs(): make the default config file match the code

- Cargo.lock
- Cargo.toml
- crates/papyrus_common/src/metrics.rs
- crates/papyrus_sync/Cargo.toml
- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1043)
> chore(monitoring,sync): emit header latency metric

- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/test_utils.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/execution_test.rs
- crates/papyrus_gateway/src/v0_4_0/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1047)
> chore(execution): separate tests and test utils to files

- Cargo.lock
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/v0_4_0/snapshots/papyrus_gateway__v0_4_0__write_api_error__write_api_error_test__starknet_error_to_declare_error_snapshot.snap
- crates/papyrus_gateway/src/v0_4_0/snapshots/papyrus_gateway__v0_4_0__write_api_error__write_api_error_test__starknet_error_to_deploy_account_error_snapshot.snap
- crates/papyrus_gateway/src/v0_4_0/snapshots/papyrus_gateway__v0_4_0__write_api_error__write_api_error_test__starknet_error_to_invoke_error_snapshot.snap
- crates/papyrus_gateway/src/v0_4_0/write_api_error_test.rs
- crates/starknet_client/src/starknet_error.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1038)
> test(JSON-RPC): add regression test for starknet error conversion

- crates/starknet_client/src/starknet_client_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1045)
> test(starknet_client): add test for BadResponseStatus error

- README.md
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/708)
> codecov readme - add badge

- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1046)
> refactor: refactor raw_call()

- .github/workflows/ci.yml
- crates/papyrus_config/src/lib.rs
- crates/papyrus_gateway/src/gateway_metrics/mod.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/v0_3_0/transaction.rs
- crates/papyrus_gateway/src/v0_4_0/transaction.rs
- crates/papyrus_load_test/src/lib.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
- crates/papyrus_node/src/bin/dump_config.rs
- crates/papyrus_node/src/lib.rs
- crates/papyrus_node/src/version.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_sync/src/lib.rs
- crates/starknet_client/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/932)
> test(JSON-RPC): add option to ignore functions in converage report

- crates/starknet_client/src/starknet_client_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1054)
> test(starknet_client): add test for StarknetError and SerdeError

- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_4_0/broadcasted_transaction_test.rs
- crates/papyrus_gateway/src/v0_4_0/error.rs
- crates/papyrus_gateway/src/v0_4_0/state.rs
- crates/papyrus_gateway/src/v0_4_0/write_api_error.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1041)
> chore(JSON-RPC): do TODOs

- crates/starknet_client/src/reader/objects/block.rs
- crates/starknet_client/src/reader/objects/block_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1050)
> fix(starknet_client): deserialize global root also with 0x1 prefix

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/996)
> ci(execution): add executable-run to the ci

- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1053)
> chore: change sync config default values

- crates/papyrus_config/src/loading.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1062)
> fix(config): remove the config_file from the cmd args before parsing it

- crates/papyrus_gateway/src/v0_3_0/block.rs
- crates/papyrus_gateway/src/v0_3_0/error.rs
- crates/papyrus_gateway/src/v0_4_0/block.rs
- crates/papyrus_gateway/src/v0_4_0/error.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1048)
> feat(): return intenral error in pending request

- crates/papyrus_gateway/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1065)
> test(JSON-RPC): fix bug in get_starknet_spec_api_schema_for_method_errors

- Cargo.lock
- config/default_config.json
- crates/papyrus_execution/Cargo.toml
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/objects.rs
- crates/papyrus_execution/src/testing_instances.rs
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/resources/V0_3_0/starknet_trace_api_openrpc.json
- crates/papyrus_gateway/resources/V0_4_0/starknet_trace_api_openrpc.json
- crates/papyrus_gateway/resources/erc20_fee_contract_class.json
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/execution_test.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1052)
> feat(execution): simulate transactions gateway endpoint

- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/execution_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1056)
> feat(execution): gateway transactionTrace endpoint

- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1040)
> chore: remove stale TODO

- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/state_reader_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1057)
> chore(execution): solve some todos

- .github/workflows/ci.yml
Starknet client integration test is not running.
- CI runs all integration tests - whether tagged as ignored or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1066)
> ci(starknet_client): fix integration test command to run all (ignored) integration tests

- Cargo.lock
- crates/papyrus_config/Cargo.toml
- crates/papyrus_config/src/config_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1064)
> test(config): test custom config from file flow

- crates/papyrus_gateway/resources/V0_4_0/starknet_write_api.json
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1069)
> test(JSON-RPC): fix bug in get_starknet_spec_api_schema_for_method_results

- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/test_utils.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/execution_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1067)
> feat(execution): disable simulate transactions and estimate fee until blockifier calc tx hashes

- crates/papyrus_config/README.md
- crates/papyrus_config/src/command.rs
- crates/papyrus_config/src/config_test.rs
- crates/papyrus_config/src/loading.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1070)
> feat(config): load many config files

- crates/papyrus_config/src/command.rs
- crates/papyrus_config/src/config_test.rs
- crates/papyrus_config/src/converters.rs
- crates/papyrus_config/src/loading.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1001)
> refactor(config): process loaded values instead of serialized params

- crates/papyrus_gateway/resources/V0_3_0/starknet_trace_api_openrpc.json
- crates/papyrus_gateway/resources/V0_4_0/starknet_trace_api_openrpc.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1071)
> test(JSON-RPC): fix other spec files

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1072)
> fix: dont run commitlint on push event

- crates/papyrus_execution/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1081)
> chore(execution): fix dev dependencies

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1083)
> ci: use stable toolchain in executable-run

- crates/papyrus_gateway/resources/V0_3_0/starknet_api_openrpc.json
- crates/papyrus_gateway/resources/V0_4_0/starknet_api_openrpc.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1078)
> fix(JSON-RPC): schema conflict fixes

- Cargo.lock
- config/default_config.json
- crates/papyrus_execution/Cargo.toml
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/test_utils.rs
- crates/papyrus_execution/src/testing_instances.rs
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1068)
> feat(execution)!: make hard-coded execution parameters configurable

- crates/papyrus_execution/src/objects.rs
- crates/papyrus_execution/src/testing_instances.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1086)
> fix(execution): fix serialization of trace

- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_3_0/error.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1080)
> feat(JSON-RPC): add schema validation to api requests

- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1076)
> feat(sync): info about verified block with base layer

- crates/papyrus_config/src/command.rs
- crates/papyrus_config/src/config_test.rs
- crates/papyrus_config/src/dumping.rs
- crates/papyrus_config/src/lib.rs
- crates/papyrus_config/src/loading.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1073)
> refactor(config): move serialized and pointer param under serialized content

- Monitoring/grafana.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1058)
> feat(monitoring): add grafana.json to the repo

- README.md
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1088)
> chore: add readme for the monitoring gateway

- config/default_config.json
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1092)
> fix(execution): set the fee costs to the correct values in Mainnet

- README.md
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1096)
> doc: readme captial letters fix

- crates/papyrus_load_test/src/lib.rs
- crates/papyrus_load_test/src/scenarios.rs
- crates/papyrus_load_test/src/transactions.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1060)
> test(load_test): add syncing endpoint to the loadtest

- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_sync/src/sources/central.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1095)
> perf: set default value for concurrent_requests to 10

- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1055)
> test(starknet_client): add more tests for StarknetFeederGatewayClient

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/error.rs
- crates/papyrus_rpc/src/v0_4_0/execution_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1074)
> feat(execution): traceBlockTransactions endpoint

- README.md
- config/default_config.json
- crates/papyrus_node/src/bin/dump_config.rs
- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main.rs
- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_rpc/src/rpc_metrics/mod.rs
- crates/papyrus_rpc/src/rpc_metrics/rpc_metrics_test.rs
- crates/papyrus_rpc/src/rpc_test.rs
- crates/papyrus_rpc/src/test_utils.rs
- crates/papyrus_rpc/src/v0_3_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1097)
> refactor(JSON-RPC): rename gateway crate to rpc

- crates/papyrus_config/src/config_test.rs
- crates/papyrus_config/src/converters.rs
- crates/papyrus_config/src/dumping.rs
- crates/papyrus_config/src/loading.rs
- crates/papyrus_rpc/src/middleware.rs
- crates/papyrus_rpc/src/v0_3_0/api/test.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/reader/objects/block.rs
- crates/starknet_client/src/starknet_error.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1103)
> chore(): fix clippy

- crates/papyrus_rpc/src/v0_4_0/transaction.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1100)
> perf(JSON-RPC): use const tx version instead of function call

- crates/papyrus_execution/config_files/default.json
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1101)
> chore: read default config from file

- .github/workflows/docker-publish.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1089)
> chore: update docker image tags

- crates/papyrus_rpc/src/test_utils.rs
- crates/papyrus_rpc/src/v0_4_0/execution_test.rs
- crates/papyrus_rpc/src/v0_4_0/write_api_error_test.rs
- crates/papyrus_rpc/src/v0_4_0/write_api_result_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1099)
> chore(JSON-RPC): rename spec files variants

- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central/state_update_stream.rs
- crates/papyrus_sync/src/sources/central_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1104)
> chore(config,sync): make state update stream configurable

- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/objects.rs
- crates/papyrus_execution/src/testing_instances.rs
- crates/papyrus_rpc/resources/V0_4_0/starknet_trace_api_openrpc.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1106)
> fix(JSON-RPC): fix the schema of TransactionTrace

- Dockerfile
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1110)
> chore: bump docker rust version

- config/default_config.json
- crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1112)
> refactor(base_layer): serialize required node url

- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1115)
> fix(JSON-RPC): avoid calling function when not needed

- crates/papyrus_common/resources/deprecated_transaction_hash.json
- crates/papyrus_common/resources/transaction_hash.json
- crates/papyrus_common/src/transaction_hash.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1117)
> feat(common): calculate invoke transaction hash

- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- feat(JSON-RPC): add type alias for DeployAccountTransaction
- feat(JSON-RPC): add starknet_addInvokeTransaction
- feat(JSON-RPC): add starknet_addDeployAccountTransaction
- test(JSON-RPC): add more tests for write_api
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1022)
> test(JSON-RPC): add more tests for write_api

- .github/workflows/ci.yml
- Cargo.toml
- Dockerfile
- commitlint.config.js
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/build.rs
- crates/papyrus_network/src/lib.rs
- crates/papyrus_network/src/messages/block.rs
- crates/papyrus_network/src/messages/common.rs
- crates/papyrus_network/src/messages/mod.rs
- crates/papyrus_network/src/messages/proto/google/protobuf/timestamp.proto
- crates/papyrus_network/src/messages/proto/p2p/proto/block.proto
- crates/papyrus_network/src/messages/proto/p2p/proto/common.proto
- docs/CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1116)
> feat(network): add block messages through protobuf

- Cargo.lock
- clippy.toml
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/get_blocks/mod.rs
- crates/papyrus_network/src/get_blocks/protocol.rs
- crates/papyrus_network/src/get_blocks/protocol_test.rs
- crates/papyrus_network/src/lib.rs
- crates/papyrus_network/src/messages/block.rs
- crates/papyrus_network/src/messages/common.rs
- crates/papyrus_network/src/messages/proto/p2p/proto/block.proto
- crates/papyrus_network/src/messages/proto/p2p/proto/common.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1122)
> feat(network): add RequestProtocol and ResponseProtocol

- crates/papyrus_common/resources/transaction_hash.json
- crates/papyrus_common/src/transaction_hash.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1124)
> feat(common): calculate declare transaction hash

- Monitoring/grafana.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1113)
> feat(monitoring): update grafana.json

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/get_blocks/handler.rs
- crates/papyrus_network/src/get_blocks/handler_test.rs
- crates/papyrus_network/src/get_blocks/mod.rs
- crates/papyrus_network/src/get_blocks/protocol.rs
- feat(network): add RequestProtocol and ResponseProtocol
- feat(network): add get_blocks::Handler with simple test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1123)
> feat(network): add get_blocks::Handler with simple test

- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1136)
> fix(config): sec instead of ms for sleep duration

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/executor/db_executor.rs
- crates/papyrus_network/src/executor/mod.rs
- crates/papyrus_network/src/executor/sync_notify_executor.rs
- crates/papyrus_network/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1145)
> feat(network): add db executor trait

- crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
- crates/papyrus_common/src/transaction_hash.rs
- crates/papyrus_config/src/loading.rs
- crates/papyrus_load_test/src/lib.rs
- crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_3_0/deprecated_contract_class.rs
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/deprecated_contract_class.rs
- crates/papyrus_storage/src/body/events.rs
- crates/starknet_client/src/reader/mod.rs
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1143)
> style(common): remove unwraps from production code

- Cargo.lock
- Cargo.toml
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/get_blocks/behaviour.rs
- crates/papyrus_network/src/get_blocks/behaviour_test.rs
- crates/papyrus_network/src/get_blocks/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1138)
> feat(network): add Behaviour that only sends requests to handler

- crates/papyrus_sync/src/sources/central_test.rs
- crates/starknet_client/resources/reader/block.json
- crates/starknet_client/resources/reader/block_state_update.json
- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/reader/objects/block.rs
- crates/starknet_client/src/reader/objects/block_test.rs
- crates/starknet_client/src/reader/objects/state.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1151)
> refactor(starknet_client): remove the special deser of global root

- crates/papyrus_execution/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1162)
> fix: remove unwrap() from code

- crates/papyrus_execution/src/execution_utils.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/objects.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1163)
> fix(execution): return error instead of panic

- crates/papyrus_rpc/src/v0_3_0/deprecated_contract_class.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/deprecated_contract_class.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1164)
> fix: remove unwraps

- config/default_config.json
- crates/papyrus_base_layer/src/ethereum_base_layer_contract.rs
- crates/papyrus_config/src/config_test.rs
- crates/papyrus_config/src/dumping.rs
- crates/papyrus_config/src/lib.rs
- crates/papyrus_config/src/representation.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
- crates/papyrus_node/src/bin/dump_config.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main.rs
- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/starknet_client/src/retry.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1155)
> feat(config): privacy level for config parameters

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1169)
> ci(common): enforce non use of unwrap

- config/default_config.json
- crates/papyrus_config/src/validators.rs
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_rpc/src/test_utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1160)
> refactor(execution): removed the ExecutionConfig struct

- crates/papyrus_common/resources/deprecated_transaction_hash.json
- crates/papyrus_common/resources/transaction_hash.json
- crates/papyrus_common/src/transaction_hash.rs
- crates/papyrus_common/src/transaction_hash_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1156)
> fix(common): accurate transaction hash validation according tx version

- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1172)
> fix(execution): fix bug in get_execution_config_for_block and add test

- Cargo.lock
- crates/papyrus_execution/Cargo.toml
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/execution_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1140)
> feat(execution): calculate transaction hashes for execution

- Cargo.lock
- Cargo.toml
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
- crates/papyrus_network/src/streamed_data_protocol/protocol.rs
- crates/papyrus_network/src/streamed_data_protocol/protocol_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1157)
> feat(network): protocols return the IO

- crates/papyrus_network/src/streamed_data_protocol/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1166)
> feat(network): create trait aliases for Query and Data

- crates/papyrus_network/src/lib.rs
- crates/papyrus_network/src/streamed_data_protocol/protocol_test.rs
- crates/papyrus_network/src/test_utils.rs
- feat(network): protocols return the IO
- feat(network): extract get_connected_stream_futures to test utils
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1167)
> feat(network): extract get_connected_stream_futures to test utils

- .github/workflows/ci.yml
- Cargo.lock
- config/default_config.json
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/src/gateway_test.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1168)
> feat(monitoring): two config representation types

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/test_utils.rs
- test(network): add create_swarm function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1176)
> test(network): add create_swarm function

- crates/papyrus_config/src/lib.rs
- crates/papyrus_load_test/src/lib.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
- crates/papyrus_node/src/bin/dump_config.rs
- crates/papyrus_node/src/lib.rs
- crates/papyrus_node/src/version.rs
- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_rpc/src/rpc_metrics/mod.rs
- crates/papyrus_rpc/src/v0_3_0/transaction.rs
- crates/papyrus_rpc/src/v0_4_0/transaction.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_sync/src/lib.rs
- crates/starknet_client/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1179)
> fix: coverage attribute rename

- Monitoring/grafana.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1135)
> feat(monitoring): update the grafana json

- crates/papyrus_rpc/src/test_utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1180)
> fix: typo fix

- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
- test(network): add create_swarm function (#1176)
- feat(network): add handler with unimplemented
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1182)
> feat(network): add handler with unimplemented

- crates/papyrus_network/src/streamed_data_protocol/protocol_test.rs
- crates/papyrus_network/src/test_utils.rs
- test(network): add create_swarm function (#1176)
- feat(network): add handler with unimplemented
- test(network): extract hardcoded_responses to test_utils and rename to hardcoded_data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1186)
> test(network): extract hardcoded_responses to test_utils and rename to hardcoded_data

- crates/starknet_client/resources/reader/pending_data.json
- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/reader/objects/mod.rs
- crates/starknet_client/src/reader/objects/pending_data.rs
- crates/starknet_client/src/reader/starknet_feeder_gateway_client_test.rs
- crates/starknet_client/tests/feeder_gateway_integration_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1153)
> feat(starknet_client): add pending request to the reader client

- Monitoring/grafana.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1195)
> feat(monitoring): update the grafana

- config/default_config.json
- config/execution_config/goerli2_config.json
- config/execution_config/goerli_config.json
- config/execution_config/integration_config.json
- config/execution_config/mainnet_config.json
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/testing_instances.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_rpc/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1197)
> feat(execution): add execution config file per network

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/streamed_data_protocol/protocol_test.rs
- crates/papyrus_network/src/test_utils.rs
- crates/papyrus_network/src/test_utils/get_stream.rs
- test(network): add create_swarm function
- test(network): change get_connected_streams to return Stream
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1177)
> test(network): change get_connected_streams to return Stream

- crates/papyrus_network/src/messages/proto/p2p/proto/block.proto
- crates/papyrus_network/src/messages/proto/p2p/proto/common.proto
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1201)
> feat(network): protobuf update

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- test(network): add create_swarm function (#1176)
- feat(network): add handler with unimplemented
- test(network): change get_connected_streams to return Stream
- test(network): move code
- test(network): fixes
- feat(network): add InboundSession struct
- test(network): extract hardcoded_responses to test_utils and rename to hardcoded_data
- feat(network): implement inbound session in handler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1189)
> feat(network): implement inbound session in handler

- Monitoring/grafana.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1202)
> feat(monitoring): grafana update

- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_storage/src/db/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1184)
> chore(storage): change default DB growth_step size

- crates/papyrus_monitoring_gateway/src/gateway_test.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1209)
> feat(monitoring): add ready function

- config/default_config.json
- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main.rs
- crates/papyrus_storage/src/base_layer.rs
- crates/papyrus_storage/src/body/events.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/db/db_test.rs
- crates/papyrus_storage/src/header.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/test_utils.rs
[optional body]
[optional footer(s)]
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1205)
> feat(storage): add storage scope flag

- Cargo.lock
- Cargo.toml
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1206)
> chore(network): uncomment behaviour

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
- chore(network): uncomment behaviour
- feat(network): add generic event common to behaviour and handler
- feat(network): move code
- feat(network): add outbound sessions to handler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1208)
> feat(network): add outbound sessions to handler

- .github/workflows/ci.yml
- Cargo.lock
- config/default_config.json
- crates/papyrus_config/src/config_test.rs
- crates/papyrus_config/src/dumping.rs
- crates/papyrus_config/src/lib.rs
- crates/papyrus_config/src/presentation.rs
- crates/papyrus_monitoring_gateway/Cargo.toml
- crates/papyrus_monitoring_gateway/src/gateway_test.rs
- crates/papyrus_monitoring_gateway/src/lib.rs
- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1192)
> feat(config): generated param type in the default config

- crates/papyrus_network/src/messages/messages_test.rs
- crates/papyrus_network/src/messages/mod.rs
- crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- crates/papyrus_network/src/streamed_data_protocol/protocol.rs
- crates/papyrus_network/src/streamed_data_protocol/protocol_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1212)
> fix(network): read_message returns None if EOF instead of empty message

- README.md
- deployments/helm/files/backup.sh
- deployments/helm/templates/configmap.yaml
- deployments/helm/templates/deployment.yaml
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1170)
> feat(config): add presets for the node config

- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1215)
> feat(network): add support to finishing outbound session

- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1216)
> feat(network): add OutboundSessionClosedByPeer event

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
- feat(network): add support to finishing outbound session
- fix(network): close the stream when finishing an inbound session
- feat(network): add OutboundSessionClosedByPeer event
- refactor(network): rename FinishSession to CloseSession
- feat(network): restore commented behaviour test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1220)
> feat(network): restore commented behaviour test

- crates/papyrus_network/src/streamed_data_protocol/handler.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1223)
> fix(network): inbound sends SessionClosedByRequest only after the session finished sending

- crates/papyrus_network/src/streamed_data_protocol/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1222)
> docs(network): add documentation to streamed_data module and the event

- Cargo.lock
- Cargo.toml
- crates/papyrus_common/resources/block_hash.json
- crates/papyrus_common/resources/deprecated_block_hash_v0.json
- crates/papyrus_common/resources/deprecated_block_hash_v1.json
- crates/papyrus_common/resources/deprecated_block_hash_v1_no_events.json
- crates/papyrus_common/resources/deprecated_block_hash_v2.json
- crates/papyrus_common/src/block_hash.rs
- crates/papyrus_common/src/block_hash_test.rs
- crates/papyrus_rpc/src/v0_3_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/starknet_client/Cargo.toml
- crates/starknet_client/src/reader/objects/block.rs
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1203)
> feat(common): calculate block body commitments

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1224)
> feat(network): add PeerId to NewInboundSession event

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
- feat(network): add PeerId to NewInboundSession event
- feat(network): convert handler event to behaviour event
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1227)
> feat(network): convert handler event to behaviour event

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
- feat(network): impl behaviour's close_session
- feat(network): impl behaviour's send_data
- feat(network): remove dial logic from streamed data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1234)
> feat(network): remove dial logic from streamed data

- crates/papyrus_execution/src/objects.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1247)
> fix(execution): skip serialization of None objects in transaction trace

- Monitoring/alerts_grafana.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1237)
> feat(monitoring): add alerts grafana

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- fix(network): notify the correct handler
- feat(network): implement on_swarm_event for events we want to ignore
- feat(network): behaviour removes closed or failed sessions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1245)
> feat(network): behaviour removes closed or failed sessions

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- fix(network): notify the correct handler
- feat(network): implement on_swarm_event for events we want to ignore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1244)
> feat(network): implement on_swarm_event for events we want to ignore

- crates/papyrus_rpc/src/test_utils.rs
- crates/papyrus_rpc/src/v0_3_0/deprecated_contract_class.rs
- crates/papyrus_rpc/src/v0_4_0/deprecated_contract_class.rs
- crates/papyrus_sync/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1253)
> chore(): solve clippy warnings

- crates/starknet_client/src/reader/mod.rs
- crates/starknet_client/src/reader/objects/mod.rs
- crates/starknet_client/src/reader/objects/test_utils.rs
- feat(pending): add should_swap function
- test(starknet_client): add reader objects get_test_instance
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1257)
> test(starknet_client): add reader objects get_test_instance

- Cargo.lock
- Cargo.toml
- commitlint.config.js
- crates/papyrus_pending/Cargo.toml
- crates/papyrus_pending/src/lib.rs
- crates/starknet_client/src/reader/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1256)
> feat(pending): add should_swap function

- .github/workflows/ci.yml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1263)
> fix: build ci in release mode

- Cargo.lock
- crates/papyrus_common/Cargo.toml
- crates/papyrus_common/src/lib.rs
- crates/papyrus_common/src/pending_classes.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1262)
> feat(common): add PendingClasses struct

- Cargo.lock
- crates/starknet_client/Cargo.toml
- crates/starknet_client/src/reader/objects/block.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1240)
> fix: disable block commitment calculation

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1271)
> feat(JSON-RPC): get_transaction_by_block_id_and_index supports pending

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1275)
> feat(JSON-RPC): get_transaction_by_hash supports pending

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1272)
> feat(JSON-RPC): get_storage_at supports pending

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1276)
> feat(JSON-RPC): get_state_update supports pending

- crates/papyrus_storage/src/db/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1266)
> fix(storage): set higher max readers

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/block.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1285)
> feat: add PendingBlockHeader struct

- .github/workflows/nightly-tests-call.yml
- .github/workflows/nightly-tests.yml
nightly-test workflow that runs gateway_integration_test has errors.
Fixed for running over macos, and conditions for slack alert messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1286)
> fix(JSON-RPC): fix slack alert mechanism in integration test

- crates/papyrus_storage/src/mmap_file/mmap_file_test.rs
- crates/papyrus_storage/src/mmap_file/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1282)
> refactor(storage): mmap append

- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/pending.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1288)
> feat(sync): update pending only when it's more advanced

- Cargo.lock
- crates/papyrus_node/src/main.rs
- crates/papyrus_sync/Cargo.toml
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sync_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1291)
> feat(sync): store old block's pending until we download pending from new block

- config/presets/mainnet.json
- config/presets/testnet1.json
- config/presets/testnet2.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1294)
> fix(config): add starknet_contract_address to presets

- Cargo.lock
- crates/papyrus_execution/Cargo.toml
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/execution_utils.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/test_utils.rs
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1296)
> feat(execution): return StateDiff induced by transaction execution

- crates/papyrus_node/src/main.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sync_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1293)
> feat(sync): sync receives pending classes lock and passes it to pending sync

- crates/papyrus_execution/src/execution_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1298)
> chore: remove redundant clone

- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1302)
> test: add testing of pending block for get_block_w_transaction_hashes()

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/test_instances.rs
- crates/papyrus_storage/src/utils.rs
- crates/papyrus_storage/src/utils_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1299)
> feat(storage)!: store contract class in a file

- crates/papyrus_rpc/src/api.rs
- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_rpc/src/rpc_test.rs
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/block.rs
- crates/papyrus_rpc/src/v0_4_0/execution_test.rs
- crates/papyrus_rpc/src/v0_4_0/transaction.rs
- crates/papyrus_rpc/src/v0_4_0/write_api_error.rs
- crates/papyrus_rpc/tests/gateway_integration_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1300)
> chore(JSON-RPC): prepare 0_4_0 to copy before creating version 0_5_0

- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/test_instances.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1306)
> feat(storage)!: store CASMs in a file

- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/state/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1307)
> refactor(storage): shared mmap write

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/data.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/test_instances.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1309)
> feat(storage)!: store deprecated classes in a file

- crates/papyrus_storage/src/header.rs
- crates/papyrus_storage/src/header_test.rs
- crates/papyrus_storage/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1328)
> fix(storage): revert starknet version

- crates/papyrus_common/src/pending_classes.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1325)
> fix(common): fix PendingClasses interface

- crates/papyrus_storage/src/serializers.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1330)
> test(storage): add CASM serde test

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/block.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1317)
> feat(JSON-RPC): get_block_transaction_count supports pending

- .github/workflows/ci.yml
- crates/papyrus_rpc/resources/V0_4_0/starknet_api_openrpc.json
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/block.rs
- crates/papyrus_rpc/src/v0_4_0/state.rs
- crates/papyrus_rpc/src/v0_4_0/transaction.rs
- crates/starknet_client/src/reader/objects/test_utils.rs
- crates/starknet_client/src/reader/objects/transaction.rs
- crates/test_utils/src/lib.rs
- feat(JSON-RPC): get_block_transaction_count supports pending
- feat(JSON-RPC): get_transaction_by_block_id_and_index supports pending
- feat(JSON-RPC): get_transaction_by_hash supports pending
- feat(JSON-RPC): get_storage_at supports pending
- feat(JSON-RPC): get_state_update supports pending
- feat: add PendingBlockHeader struct
- feat: support pending block in get_block_w_transaction_hashes()
- feat(JSON-RPC): get_transaction_receipt supports pending
- disable commitlint
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1332)
> disable commitlint

- crates/papyrus_rpc/resources/V0_4_0/starknet_api_openrpc.json
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1304)
> feat: support pending block for get_block_w_full_transactions

- crates/papyrus_rpc/resources/V0_4_0/starknet_api_openrpc.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1341)
> fix: improve pending block schemas

- crates/papyrus_common/src/pending_classes.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/starknet_client/src/reader/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1337)
> refactor(common): unite PendingClass with ApiContractClass

- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/central_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1338)
> feat(sync): add get_class/get_compiled_class to central source

- crates/papyrus_storage/src/db/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1301)
> chore(storage): set higher max readers

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1342)
> feat(storage)!: compress thin state diff

- Cargo.lock
- Cargo.toml
- crates/papyrus_common/resources/block_hash.json
- crates/papyrus_common/resources/deprecated_block_hash_v0.json
- crates/papyrus_common/resources/deprecated_block_hash_v1.json
- crates/papyrus_common/resources/deprecated_block_hash_v1_no_events.json
- crates/papyrus_common/resources/deprecated_block_hash_v2.json
- crates/papyrus_common/src/block_hash.rs
- crates/papyrus_common/src/block_hash_test.rs
- crates/papyrus_rpc/src/v0_3_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/utils_test.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/starknet_client/src/reader/objects/block.rs
- crates/test_utils/src/lib.rs
This reverts commit 56f4eff4be5c79f82b2aa71e2f67eda24c6b0fb7.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1344)
> revert(common): calculate block body commitments (#1203)

- crates/papyrus_sync/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1340)
> feat(sync): revert doesnt clear pending data and classes

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1343)
> feat(JSON-RPC): get_tx_by_block_idx returns invalid index if pending data is not on top of head

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1346)
> perf(execution,JSON-RPC): spawn execution in a separate thread

- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_storage/src/body/events.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/test_utils/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1347)
> test(JSON-RPC): make get_events test more readable and add coverage

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1349)
> fix: read_pending_data() for get_block api-s

- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_sync/src/sources/central.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1356)
> perf(sync): set higher class cache

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1358)
> perf(storage)!: conditionally compress transactions

- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1362)
> refactor(storage): use generic mmap handler

- crates/papyrus_storage/src/mmap_file/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1365)
> refactor(storage): flush mmap according to dirty-bit

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1351)
> fix: read_pending_data() for get_storage_at

- Cargo.lock
- Cargo.toml
- crates/starknet_client/Cargo.toml
- crates/starknet_client/src/reader/objects/block_test.rs
- crates/starknet_client/src/reader/objects/transaction_test.rs
- crates/starknet_client/src/starknet_error_test.rs
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1355)
> chore: remove redundant assert dependency

- crates/papyrus_rpc/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1366)
> test(JSON-RPC): test that get_block.. returns correct sequencer address and timestamp

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1364)
> fix: read_pending_data() for get_transaction_by_hash

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1350)
> feat(JSON-RPC): get_class_hash_at supports pending with up-to-date check

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1370)
> fix: read_pending_data() for get_block_transaction_count()

- crates/papyrus_config/README.md
Added section to papyrus_config READMe on viewing online documentation and generating it locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1359)
> docs: papyrus_config: Added section on viewing online documentation and generating it locally.

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1348)
> feat(JSON-RPC): get_class supports pending

- Cargo.lock
- crates/papyrus_proc_macros/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1378)
> chore: update proc macros dependencies

- crates/papyrus_proc_macros/Cargo.toml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1379)
> chore: add proc macro crate description

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1376)
> feat: support pending block for get_nonce()

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/version.rs
- crates/papyrus_storage/src/version_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1374)
> feat: split storage version to 2 values

- crates/papyrus_storage/src/version_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1382)
> chore(storage): remove redundant clones

- crates/papyrus_node/src/version.rs
- crates/papyrus_storage/src/version_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1383)
> chore(release): bump node version to 0.2.0-dev

- crates/papyrus_common/src/lib.rs
- crates/papyrus_common/src/state.rs
- crates/starknet_client/src/reader/objects/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1381)
> refactor(starknet_client): move small structs of StateDiff to common

- crates/papyrus_execution/src/lib.rs
- crates/papyrus_rpc/src/v0_4_0/broadcasted_transaction.rs
- crates/papyrus_rpc/src/v0_4_0/execution_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1375)
> test(execution): test that executing tx in a different block context produces different result

- crates/papyrus_storage/src/compression_utils.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/test_instances.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1361)
> style(storage): style improvement of transaction serialization

- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/objects.rs
- crates/papyrus_execution/src/state_reader.rs
- crates/papyrus_execution/src/state_reader_test.rs
- crates/papyrus_execution/src/test_utils.rs
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1386)
> feat(execution): add pending members to ExecutionStateReader

- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/pending_sync.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1372)
> refactor(sync): move pending sync to a separate module

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1392)
> fix: read_pending_data() for get_transaction_receipt()

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/state.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1390)
> fix: read_pending_data() for get_state_update()

- crates/papyrus_storage/src/version_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1398)
> fix(storage): test version separately for blocks and state

- crates/starknet_client/src/reader/objects/block_test.rs
- crates/starknet_client/src/reader/objects/transaction_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1399)
> fix(): expose the deserialization error when tests fail

- crates/papyrus_rpc/resources/V0_4_0/starknet_api_openrpc.json
- crates/papyrus_rpc/src/test_utils.rs
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1303)
> feat(JSON-RPC): add pending support for get_events with minimal test

- config/default_config.json
- config/presets/mainnet.json
- config/presets/testnet1.json
- config/presets/testnet2.json
- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_node/src/bin/dump_config.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1373)
> chore(config): unite the values of rpc.starknet_url and central.url

- Cargo.lock
- Cargo.toml
- crates/papyrus_common/resources/block_hash.json
- crates/papyrus_common/resources/deprecated_block_hash_v0.json
- crates/papyrus_common/resources/deprecated_block_hash_v1.json
- crates/papyrus_common/resources/deprecated_block_hash_v1_no_events.json
- crates/papyrus_common/resources/deprecated_block_hash_v2.json
- crates/papyrus_rpc/src/v0_3_0/transaction.rs
- crates/papyrus_rpc/src/v0_4_0/transaction.rs
- crates/papyrus_storage/src/body/events.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/test_instances.rs
- crates/starknet_client/src/reader/objects/test_utils.rs
- crates/starknet_client/src/reader/objects/transaction.rs
- crates/test_utils/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1401)
> feat()!: store ExecutionResources as part of transaction output

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1397)
> feat: support pending data for get_class_at()

- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
This reverts commit b7c828966f1df3eb9880b5c60c0bc749bc03e993.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1405)
> chore(JSON-RPC): revert 'feat: support pending data for get_class_at() (#1397)'

- crates/papyrus_rpc/src/v0_4/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4/api/mod.rs
- crates/papyrus_rpc/src/v0_4/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1406)
> feat: support pending data for get_class_at() (#1397)

- crates/papyrus_execution/src/execution_utils.rs
- crates/papyrus_execution/src/state_reader.rs
- crates/papyrus_execution/src/state_reader_test.rs
- crates/papyrus_rpc/src/v0_4/api/api_impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1407)
> feat(execution): pending support for ExecutionStateReader::get_storage_at

- crates/papyrus_execution/src/execution_utils.rs
- crates/papyrus_execution/src/state_reader.rs
- crates/papyrus_execution/src/state_reader_test.rs
- crates/papyrus_rpc/src/v0_4/api/api_impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1410)
> feat(execution): pending support for ExecutionStateReader::get_class_hash_at

- crates/papyrus_sync/src/pending_sync.rs
- crates/papyrus_sync/src/sync_test.rs
- crates/starknet_client/src/reader/objects/pending_data.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1402)
> fix(sync): pending sync handles the block_hash field correctly

- crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
- crates/papyrus_rpc/src/v0_5/api/api_impl.rs
- crates/papyrus_rpc/src/v0_5/api/mod.rs
- crates/papyrus_rpc/src/v0_5/api/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1411)
> feat(JSON-RPC): new method spec_version

- crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1417)
> chore(JSON-RPC): delete pendingTransactions from spec

- crates/papyrus_rpc/resources/V0_5/starknet_api_openrpc.json
- crates/papyrus_rpc/src/v0_5/api/api_impl.rs
- crates/papyrus_rpc/src/v0_5/api/test.rs
- crates/papyrus_rpc/src/v0_5/block.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1416)
> feat(JSON-RPC): add l1_gas_price and starknet_version to block header

- crates/papyrus_execution/src/state_reader.rs
- crates/papyrus_execution/src/state_reader_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1414)
> feat(execution): pending support for ExecutionStateReader::get_compiled_class_hash_at

- crates/papyrus_execution/src/state_reader.rs
- crates/papyrus_execution/src/state_reader_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1418)
> feat(execution): pending support for ExecutionStateReader::get_compiled_contract_class

- crates/papyrus_rpc/resources/V0_5/starknet_trace_api_openrpc.json
- crates/papyrus_rpc/src/v0_5/execution.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1419)
> feat(JSON-RPC): add type to transaction trace
