- crates/papyrus_node/src/config/file_config.rs
Users can add unknown configuration parameters and the node will not produce an error. 
This is prone to spelling mistakes and other human errors.
Users will get an error when running the node
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/468)
> Fail config loading on unknown parameters

- crates/starknet_client/Cargo.toml
- crates/starknet_client/src/lib.rs
This PR add [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) 
Issue Number: #497 
HTTP request now contains [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent), e.g.:
```
GET /feeder_gateway/get_block HTTP/1.1
accept: */*
user-agent: papyrus/pre-release (Arch Linux; Rolling Release; 64-bit)
host: localhost:5555
```
Operating system informations are retrieved with [os_info](https://docs.rs/crate/os_info/latest)
Please not that version is hardcoded to `pre-release`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/556)
> Add user-agent in HTTP request

- crates/papyrus_node/src/bin/central_source_integration_test.rs
- crates/papyrus_node/src/main.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/papyrus_sync/src/sources/central_test.rs
- crates/papyrus_sync/src/sources/stream_utils.rs
- crates/starknet_client/src/lib.rs
- crates/starknet_client/src/starknet_client_test.rs
Downloads a class even if it was downloaded before.
Before downloading a deprecated class, try to retrieve it from the storage. 
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/603)
> Download deprecated classes not in storage

- crates/test_utils/src/lib.rs
**Stack**:
- #639
- #638
- #637
- #636
- #635
- #634
- #633
- #632 ⬅
- #631
- #630
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/632)
> remove unused function - get_rand_test_block

- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/ommer/ommer_test.rs
- crates/papyrus_storage/src/serializers_test.rs
- crates/test_utils/src/lib.rs
dibatable lose of functionality but simplifies the code so I think it worth it.
also, there's still the ability to pass the seed as env var in order to debug when needed.
commit-id:a694971d
---
**Stack**:
- #639 ⬅
- #638
- #637
- #636
- #635
- #634
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/639)
> Remove the option to dynamically pass seed to rng generator

- Cargo.toml
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_storage/src/state/state_test.rs
SN API now has casts for each unsigned type, need to avoid ambiguity.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/684)
> Bump SN API version + fix casts

- Cargo.lock
- config/default_config.json
- crates/papyrus_config/Cargo.toml
- crates/papyrus_config/src/lib.rs
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/lib.rs
- crates/papyrus_gateway/src/snapshots/papyrus_gateway__gateway_test__dump_default_config.snap
- A dump file for configurations with the default values and the members' descriptions.
- Currently only for the gateway config.
- [ x] No
The default config yaml file is flattened and structured as follows:
\- - variable path
\- variable Description
\- default value
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/723)
> Add dump trait for sub configs.

- deployments/helm/templates/deployment.yaml
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/789)
> modify chart to support nodeSelector and tolerations

- crates/papyrus_gateway/src/v0_3_0/broadcasted_transaction.rs
- crates/papyrus_gateway/src/v0_3_0/broadcasted_transaction_test.rs
- crates/starknet_reader_client/src/writer/objects/response.rs
- crates/starknet_reader_client/src/writer/objects/response_test.rs
- crates/starknet_reader_client/src/writer/objects/test_utils.rs
- crates/starknet_reader_client/src/writer/objects/transaction.rs
- crates/starknet_reader_client/src/writer/objects/transaction_test.rs
- crates/test_utils/src/lib.rs
- move writer client into reader client crate
- fix(starknet_client): Use crate instead of super
- refactor(starknet_client)!: remove Transaction and AddTransactionResponse (But keeping the variant structs)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/905)
> shahak/sn writer client/remove transaction enum

- crates/starknet_client/src/writer/mod.rs
- crates/starknet_client/src/writer/starknet_gateway_client_test.rs
- move common client functionality to StarknetBaseClient
- change request_with_retry to receive a RequestBuilder instead of Url
- move writer client into reader client crate
- add StarknetGatewayClient
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/901)
> shahak/sn writer client/starknet gateway client

- Cargo.lock
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/api.rs
- crates/papyrus_gateway/src/gateway_test.rs
- crates/papyrus_gateway/src/middleware.rs
- crates/papyrus_gateway/src/test_utils.rs
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/api/mod.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_3_0/broadcasted_transaction_test.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/mod.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
- crates/papyrus_gateway/src/version_config.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/929)
> feat(JSON-RPC): support version without patch

- crates/starknet_client/src/writer/starknet_gateway_client_test.rs
- refactor(starknet_client): split error into ClientError and ReaderClientError
- test(starknet_client): add writer client test for serde error in response
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/935)
> shahak/sn writer client/serde error test

- Cargo.lock
- Cargo.toml
- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/v0_4_0/error.rs
- crates/papyrus_gateway/src/v0_4_0/write_api_error.rs
- crates/papyrus_gateway/src/v0_4_0/write_api_error_test.rs
- crates/starknet_client/Cargo.toml
- crates/starknet_client/src/starknet_error.rs
- refactor(JSON-RPC): move code around
- refactor(JSON-RPC): split JsonRpcError for each error
- feat(JSON-RPC): add more errors for 0.4.0 JsonRpcError
- feat(JSON-RPC): use JsonRpcError for write_api errors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1004)
> feat(JSON-RPC): use JsonRpcError for write_api errors

- crates/papyrus_gateway/Cargo.toml
- crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_3_0/api/test.rs
- crates/papyrus_gateway/src/v0_4_0/api/api_impl.rs
- crates/papyrus_gateway/src/v0_4_0/api/test.rs
When handling a get_storage_at request in the gateway, need to check first if the contract address is 1,
the contract address for the block hash table.
If it is, we need to return a value and not a ContractNotFound error.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1000)
> fix: add check for address 1 in gateway:get_storage_at

- crates/papyrus_execution/src/objects.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/execution_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1102)
> chore(JSON-RPC,execution): consolidate repeating test code

- crates/papyrus_common/resources/deprecated_transaction_hash.json
- crates/papyrus_common/resources/transaction_hash.json
- crates/papyrus_common/src/transaction_hash.rs
- crates/papyrus_common/src/transaction_hash_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1132)
> fix: fix the deprecated L1_Handler transaction hash computation

- crates/papyrus_network/src/get_blocks/behaviour.rs
- crates/papyrus_network/src/get_blocks/behaviour_test.rs
- crates/papyrus_network/src/get_blocks/handler.rs
- crates/papyrus_network/src/get_blocks/handler_test.rs
- crates/papyrus_network/src/get_blocks/mod.rs
- crates/papyrus_network/src/get_blocks/protocol.rs
- crates/papyrus_network/src/get_blocks/protocol_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1152)
> fix(network): nake behaviour generic

- crates/papyrus_storage/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1128)
> style(storage): order the tables of the db

- config/presets/mainnet.json
- config/presets/testnet1.json
- config/presets/testnet2.json
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1199)
> feat(config): add preset files of starknet networks

- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler/session.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1214)
> fix(network): close the stream when finishing an inbound session

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- feat(network): add support to finishing outbound session
- fix(network): close the stream when finishing an inbound session
- feat(network): add OutboundSessionClosedByPeer event
- refactor(network): rename FinishSession to CloseSession
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1218)
> refactor(network): rename FinishSession to CloseSession

- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1221)
> feat(network): add SessionClosedByRequest event

- crates/papyrus_node/src/main.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central_sync_test.rs
- crates/papyrus_sync/src/sources/mod.rs
- crates/papyrus_sync/src/sources/pending.rs
- crates/papyrus_sync/src/sources/pending_test.rs
- crates/papyrus_sync/src/sync_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1175)
> feat(sync): sync pending data

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
- feat(network): add PeerId to NewInboundSession event
- feat(network): convert handler event to behaviour event
- feat(network): impl behaviour's on_connection_handler_event
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1228)
> feat(network): impl behaviour's on_connection_handler_event

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
- feat(network): add PeerId to NewInboundSession event
- feat(network): convert handler event to behaviour event
- feat(network): impl behaviour's on_connection_handler_event
- feat(network): impl behaviour's close_session
- feat(network): impl behaviour's send_data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1230)
> feat(network): impl behaviour's send_data

- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/utils.rs
- crates/papyrus_storage/src/utils_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1239)
> feat(storage): add dump storage table to file utility

- crates/papyrus_node/src/main.rs
- crates/papyrus_rpc/src/api.rs
- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_rpc/src/rpc_test.rs
- crates/papyrus_rpc/src/test_utils.rs
- crates/papyrus_rpc/src/v0_3_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_3_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- feat(storage): add db table iterator (#1235)
- feat(storage): add dump storage table to file utility (#1239)
- feat(storage): add an executable that dumps the declared_class table … (#1241)
- fix(execution): skip serialization of None objects in transaction trace (#1247)
- fix(execution): execution of declare txs - fetch the class from the r… (#1236)
- chore(config): add infomative prints to the configuration validations… (#1188)
- feat(monitoring): add alerts grafana (#1237)
- feat(): more details and changes to de table stats (#1194)
- chore(): solve clippy warnings (#1253)
- fix(common): v3 transaction hash calculation (#1210)
- feat(common): add PendingClasses struct
- feat(rpc): store pending data and classes in rpc
- - -
This change is [<img …
> feat(JSON-RPC): store pending data and classes in rpc

- crates/papyrus_storage/src/utils.rs
- crates/papyrus_storage/src/utils_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1277)
> chore(storage): remove redundant clones

- .github/workflows/nightly-tests-call.yml
- .github/workflows/nightly-tests.yml
gateway_integration_test failure fails the workflow with no alert.
- A failure will trigger sending an error message to Slack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1273)
> test(JSON-RPC): send a slack alert upon GW integration test failure

- crates/papyrus_storage/src/mmap_file/mod.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1281)
> refactor(storage): use common file handler

- Cargo.lock
- crates/dump_declared_classes/Cargo.toml
- crates/dump_declared_classes/src/main.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/utils.rs
- crates/papyrus_storage/src/utils_test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1283)
> feat: dump_declared_classes can dump for a specific block range

- crates/papyrus_rpc/resources/V0_4_0/starknet_api_openrpc.json
- crates/papyrus_rpc/src/v0_4_0/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4_0/api/mod.rs
- crates/papyrus_rpc/src/v0_4_0/api/test.rs
- crates/papyrus_rpc/src/v0_4_0/transaction.rs
- crates/starknet_client/src/reader/objects/test_utils.rs
- crates/starknet_client/src/reader/objects/transaction.rs
- crates/test_utils/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1284)
> feat(JSON-RPC): get_transaction_receipt supports pending

- crates/dump_declared_classes/src/main.rs
- crates/papyrus_storage/src/utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1295)
> fix: dump_decalared_classes fix goerli

- .github/workflows/ci.yml
- .github/workflows/nightly-tests-call.yml
- rustfmt.toml
Using `actions-rs/toolchain` in workflows.
Using `dtolnay/rust-toolchain` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1289)
> ci: replace non-maintained actions-rs/toolchain with dtolnay/rust-toolchain

- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/db/db_test.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/mmap_file/mmap_file_test.rs
- crates/papyrus_storage/src/mmap_file/mod.rs
- crates/papyrus_storage/src/serializers.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/test_instances.rs
- crates/papyrus_storage/src/test_utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1290)
> feat(storage): store thin state diff in a file

- .github/workflows/ci.yml
- .github/workflows/docker-publish.yml
- .github/workflows/helm-install.yml
- .github/workflows/nightly-tests-call.yml
Use of actions/checkout@v3 in workflows.
Use v4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1297)
> ci: bump actions/checkout action from v3 to v4

- crates/papyrus_load_test/src/create_files.rs
- crates/papyrus_rpc/tests/gateway_integration_test.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/state/mod.rs
Replaced with unwrap_or_else so that string allocation will only accure in the errorneous case.
Error messages are printed with a variable name instead of its value.
- The value is printed.
- The error message string will only be computed and allocated in case the error case was actually reached.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1329)
> fix: replace expect when using format strings in error message

- crates/papyrus_common/src/pending_classes.rs
- refactor(storage): shared mmap write (#1307)
- feat(storage)!: store deprecated classes in a file (#1309)
- fix(storage): revert starknet version (#1328)
- chore(execution,JSON-RPC): order field of events and messages, 0.4 s… (#1305)
- test(starknet_client): add get_test_instance to ContractClass (#1327)
- fix(common): fix PendingClasses interface (#1325)
- feat(starknet_client): add conversion from ContractClass to PendingClass (#1326)
- test(storage): add CASM serde test (#1330)
- feat(JSON-RPC): get_block_transaction_count supports pending (#1317)
- feat(JSON-RPC): get_transaction_by_block_id_and_index supports pending (#1318)
- feat(JSON-RPC): get_transaction_by_hash supports pending (#1319)
- feat(JSON-RPC): get_storage_at supports pending
- feat(JSON-RPC): get_state_update …
> feat(common): pending classes stores compiled classes by class hash

- .github/workflows/nightly-tests-call.yml
A filed test in nightly-test-call doesn't fail the job (and the workflow is marked as successful in the Github Actions UI).
Fail the job if the test failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1334)
> ci: fail GW-integration-test-call job upon test failue

- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/db/db_test.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/header.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/state/mod.rs
When trying to insert a key that already exists to the internal DB in papyrus_storage, an error with no info is given by default.
Table name, key, and value are logged in the new error.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1353)
> feat(storage): add a detailed default error message when inserting existing key to DB

- crates/papyrus_storage/src/body/body_test.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/compiled_class_test.rs
- crates/papyrus_storage/src/header.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_sync/src/lib.rs
Many unique KeyAlreadyExists errors exist for different objects.
A single error for all.
Replacing existing error types:
`StorageError::{BlockHashAlreadyExists, TransactionHashAlreadyExists,  ContractAlreadyExists, CompiledClassReWrite,  StarknetVersionAlreadyExists, ClassAlreadyExists}`
with: `StorageError::InnerError::KeyAlreadyExists`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1357)
> feat(storage): remove the different already exists errors

- crates/papyrus_common/src/lib.rs
- crates/papyrus_common/src/state.rs
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/execution_utils.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/objects.rs
- crates/papyrus_execution/src/state_reader.rs
- crates/papyrus_execution/src/state_reader_test.rs
- crates/papyrus_execution/src/test_utils.rs
- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_rpc/src/state.rs
- crates/papyrus_rpc/src/v0_4/api/api_impl.rs
- crates/papyrus_rpc/src/v0_4/execution_test.rs
- crates/papyrus_rpc/src/v0_5/api/api_impl.rs
- crates/starknet_client/src/reader/objects/state.rs
- refactor(starknet_client): move small structs of StateDiff to common (#1381)
- feat(execution): add pending members to ExecutionStateReader (#1386)
- feat(execution): pending support for ExecutionStateReader::get_storage_at (#1407)
- feat(execution): pending support for ExecutionStateReader::get_class_hash_at (#1410)
- feat(execution): pending support for ExecutionStateReader::get_compiled_class_hash_at (#1414)
- feat(execution): pending support for ExecutionStateReader::get_compiled_contract_class (#1418)
- feat(execution): pending support for ExecutionStateReader::get_nonce (#1420)
- fix(execution): get_compiled_contract_class looks for pending deprecated classes (#1426)
- fix(execution): verify_contract_exists looks at pending as well (#1425)
- feat(JSON-RPC): add support for pending …
> feat(JSON-RPC): add support for pending to call (#1427)

- crates/papyrus_rpc/src/test_utils.rs
- crates/papyrus_rpc/src/v0_4/api/test.rs
- fix(JSON-RPC): validate the type of transaction in write api methods
- fix(JSON-RPC): validate that the version field of transaction matches
- test(JSON-RPC): test params spec of write api methods
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1543)
> test(JSON-RPC): test params spec of write api methods

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- feat(network): add block messages through protobuf (#1116)
- feat(network): add read_message and write_message (#1121)
- feat(network): add RequestProtocol and ResponseProtocol (#1122)
- feat(network): add get_blocks::Handler with simple test (#1123)
- feat(network): add db executor trait (#1145)
- feat(network): add Behaviour that only sends requests to handler (#1138)
- fix(network): nake behaviour generic (#1152)
- refactor(network): rename get_blocks to streamed_data_protocol (#1154)
- feat(network): add methods to finish sessions without impl (#1158)
- feat(network): create trait aliases for Query and Data (#1166)
- fix(network): unite clippy.toml with .clippy.toml
- feat(network): extract get_connected_stream_futures to test utils …
> fix(network): add dial error support to handler

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/behaviour_test.rs
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- crates/papyrus_network/src/streamed_data_protocol/mod.rs
- feat(network): add block messages through protobuf (#1116)
- feat(network): add read_message and write_message (#1121)
- feat(network): add RequestProtocol and ResponseProtocol (#1122)
- feat(network): add get_blocks::Handler with simple test (#1123)
- feat(network): add db executor trait (#1145)
- feat(network): add Behaviour that only sends requests to handler (#1138)
- fix(network): nake behaviour generic (#1152)
- refactor(network): rename get_blocks to streamed_data_protocol (#1154)
- feat(network): add methods to finish sessions without impl (#1158)
- feat(network): create trait aliases for Query and Data (#1166)
- fix(network): unite clippy.toml with .clippy.toml
- feat(network): extract get_connected_stream_futures to test utils …
> feat(network): impl From<Inbound/OutboundSessionId> for SessionId

- crates/papyrus_network/src/streamed_data_protocol/behaviour.rs
- crates/papyrus_network/src/streamed_data_protocol/handler.rs
- crates/papyrus_network/src/streamed_data_protocol/handler/session.rs
- crates/papyrus_network/src/streamed_data_protocol/handler_test.rs
- fix(network): wake inbound session when there's a new data
- feat(network): check in InboundSession if outbound peer closed session
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1569)
> feat(network): check in InboundSession if outbound peer closed session

- crates/papyrus_network/src/messages/messages_test.rs
- crates/papyrus_network/src/messages/mod.rs
- crates/papyrus_network/src/streamed_data/handler.rs
- crates/papyrus_network/src/streamed_data/handler/inbound_session.rs
- crates/papyrus_network/src/streamed_data/handler_test.rs
- crates/papyrus_network/src/streamed_data/protocol.rs
- crates/papyrus_network/src/streamed_data/protocol_test.rs
- revert(network): revert InboundSession checks if outbound closed
- revert(network): outbound session closes its write half upon closing (#1571)
- revert(network): small fixes to revert commit
- feature(network): send/read query without length prefix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1642)
> feat(network): send/read query without length prefix

- crates/papyrus_network/src/bin/streamed_data_benchmark.rs
- build(network): clean up benchmark code
- build(network): close benchmark executable when there's no connection for 10 seconds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1620)
> build(network): close benchmark executable when there's no connection for 10 seconds

- crates/papyrus_network/src/block_headers/behaviour.rs
- crates/papyrus_network/src/block_headers/behaviour_test.rs
- crates/papyrus_network/src/block_headers/mod.rs
- crates/papyrus_network/src/network_manager.rs
- crates/papyrus_network/src/streamed_data/behaviour.rs
- crates/papyrus_network/src/streamed_data/behaviour_test.rs
- crates/papyrus_network/src/streamed_data/handler.rs
- crates/papyrus_network/src/streamed_data/handler_test.rs
- revert(network): remove close_outbound_session
- feature(network): drop inbound session when failing to parse query
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1652)
> feat(network): drop inbound session when failing to parse query

- crates/papyrus_network/src/block_headers/behaviour.rs
- crates/papyrus_network/src/block_headers/behaviour_test.rs
- crates/papyrus_network/src/block_headers/mod.rs
- feature(network): drop inbound session when failing to parse query
- feat(network): add ProtobufConversionError to SessionError
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1654)
> feat(network): add ProtobufConversionError to SessionError

- crates/papyrus_storage/src/db/db_test.rs
- crates/papyrus_storage/src/db/serialization.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1710)
> feat(storage): wrapper class for versioned objects

- crates/papyrus_network/src/bin/p2p_integration_endpoint.rs
- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/swarm_trait.rs
- crates/papyrus_network/src/network_manager/test.rs
- crates/papyrus_node/src/main.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1739)
> feat(network): dial peer in network run function

- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_p2p_sync/src/lib.rs
- crates/papyrus_p2p_sync/src/p2p_sync_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1800)
> fix(sync): sleep when sync receives None and remove timeout hack

- Cargo.lock
- crates/papyrus_p2p_sync/Cargo.toml
- crates/papyrus_p2p_sync/src/header.rs
- crates/papyrus_p2p_sync/src/lib.rs
- crates/papyrus_p2p_sync/src/stream_factory.rs
- fix(sync): sleep when sync receives None and remove timeout hack
- refactor(sync): make changes to allow easily adding more types to sync
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1803)
> refactor(sync): make changes to allow easily adding more types to sync

- .github/workflows/ci.yml
- commitlint.config.js
- crates/papyrus_node/Cargo.toml
- crates/papyrus_node/src/bin/dump_config.rs
- crates/papyrus_node/src/config/config_test.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_node/src/config/pointers.rs
- crates/papyrus_node/src/main.rs
- crates/papyrus_node/src/main_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1689)
> build: add option to compile the node without rpc

- crates/papyrus_network/src/converters/protobuf_conversion/state_diff.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1818)
> fix(network): remove empty storage diffs when converting to protobuf

- Cargo.lock
- Cargo.toml
- config/default_config.json
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_p2p_sync/Cargo.toml
- crates/papyrus_p2p_sync/src/header.rs
- crates/papyrus_p2p_sync/src/lib.rs
- crates/papyrus_p2p_sync/src/p2p_sync_test.rs
- crates/papyrus_p2p_sync/src/state_diff.rs
- crates/papyrus_p2p_sync/src/stream_factory.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1812)
> feat(sync): add state diff sync to p2p sync

- crates/papyrus_storage/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1827)
> chore(storage): bump storage version after state_diff_length and receipts_commitment PR

- config/default_config.json
- config/execution/goerli_integration.json
- config/execution/goerli_testnet.json
- config/execution/mainnet.json
- config/execution/sepolia_integration.json
- config/execution/sepolia_testnet.json
- config/presets/goerli_integration.json
- config/presets/goerli_testnet.json
- config/presets/mainnet.json
- config/presets/sepolia_integration.json
- config/presets/sepolia_testnet.json
- crates/papyrus_execution/src/execution_test.rs
- crates/papyrus_execution/src/lib.rs
- crates/papyrus_execution/src/test_utils.rs
- crates/papyrus_execution/src/testing_instances.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main_test.rs
- crates/papyrus_rpc/src/lib.rs
- crates/papyrus_rpc/src/test_utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1828)
> refactor(config): move execution config to default

- crates/papyrus_execution/src/state_reader_test.rs
- crates/papyrus_execution/src/test_utils.rs
- crates/papyrus_network/src/db_executor/test.rs
- crates/papyrus_rpc/src/rpc_metrics/rpc_metrics_test.rs
- crates/papyrus_rpc/src/v0_4/api/test.rs
- crates/papyrus_rpc/src/v0_4/execution_test.rs
- crates/papyrus_rpc/src/v0_5/api/test.rs
- crates/papyrus_rpc/src/v0_5/execution_test.rs
- crates/papyrus_rpc/src/v0_6/api/test.rs
- crates/papyrus_rpc/src/v0_6/execution_test.rs
- crates/papyrus_rpc/src/v0_7/api/test.rs
- crates/papyrus_rpc/src/v0_7/execution_test.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_storage/src/state/state_test.rs
- crates/papyrus_sync/src/lib.rs
- crates/papyrus_sync/src/sources/central_test.rs
- fix(storage): revert_state_diff works if there are missing classes
- fix(sync): use append_thin_state_diff in sync
- fix: use append_thin_state_diff in network and execution
- fix: use append_thin_state_diff in rpc
- chore(storage): remove append_state_diff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1890)
> chore(storage): remove append_state_diff

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/lib.rs
- crates/papyrus_network/src/peer_manager/mod.rs
- crates/papyrus_network/src/peer_manager/peer.rs
- crates/papyrus_network/src/peer_manager/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1874)
> feat(network): add peer manager struct - not used yet

- .github/workflows/ci.yml
- crates/papyrus_storage/src/mmap_file/mmap_file_test.rs
- crates/papyrus_storage/src/mmap_file/mod.rs
- deployments/helm/values.yaml
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1864)
> chore: update image tag for v0.3

- Cargo.lock
- config/default_config.json
- crates/papyrus_common/src/metrics.rs
- crates/papyrus_node/src/config/mod.rs
- crates/papyrus_node/src/config/snapshots/papyrus_node__config__config_test__dump_default_config.snap
- crates/papyrus_node/src/main.rs
- crates/papyrus_proc_macros/Cargo.toml
- crates/papyrus_proc_macros/src/lib.rs
- crates/papyrus_proc_macros/tests/latency_histogram.rs
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/class.rs
- crates/papyrus_storage/src/compiled_class.rs
- crates/papyrus_storage/src/state/mod.rs
- crates/papyrus_sync/src/lib.rs
- papyrus_utilities.Dockerfile
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1867)
> feat: add ability to config profiling on/off

- crates/papyrus_network/src/lib.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1925)
> docs(network): add docs for some of the public structs

- .github/workflows/ci.yml
- .github/workflows/nightly-tests.yml
- Cargo.lock
- crates/papyrus_storage/Cargo.toml
- crates/papyrus_storage/src/db/table_types/dup_sort_tables_test.rs
- crates/papyrus_storage/src/db/table_types/test_utils.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1816)
> test(storage): add random table test

- crates/papyrus_network/src/discovery/flow_test.rs
- crates/papyrus_network/src/discovery/identify_impl.rs
- crates/papyrus_network/src/discovery/mod.rs
- crates/papyrus_network/src/main_behaviour/mixed_behaviour.rs
- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/streamed_bytes/mod.rs
- crates/papyrus_network/src/test_utils/mod.rs
- feat(network): call Kad::add_address on bootstrap peer
- feat(network): catch more swarm events in network manager (#1926)
- fix(network): remove peer id from network manager (#1927)
- feat(network): use start_query in swarm trait (#1929)
- feat(network): add tracing info to behaviours (#1928)
- test(storage): add random table test (#1816)
- fix(network): remove unneeded failing test (#1934)
- refactor: remove unnecessary dead_code annotations (#1933)
- test(network): discovery flow test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1940)
> test(network): discovery flow test

- crates/papyrus_network/src/peer_manager/behaviour_impl.rs
- crates/papyrus_network/src/peer_manager/mod.rs
- crates/papyrus_network/src/peer_manager/peer.rs
- crates/papyrus_network/src/peer_manager/test.rs
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1948)
> feat(network): pm support multiple connection ids

- crates/papyrus_network/src/streamed_bytes/behaviour.rs
- crates/papyrus_network/src/streamed_bytes/handler.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1976)
> refactor(network): remove OtherOutboundPeerSentData from SessionError enum

- crates/papyrus_network/src/db_executor/mod.rs
- crates/papyrus_network/src/db_executor/test.rs
- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/test.rs
rename `DBExecutor` to `DBExecutorTrait`, and `BlockHeaderDBExecutor` to `DBExecutor`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1977)
> refactor(network): rename BlockHeaderDBExecutor to DBExecutor

- crates/papyrus_network/src/broadcast/mod.rs
- crates/papyrus_network/src/mixed_behaviour.rs
- crates/papyrus_network/src/network_manager/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1982)
> feat(network): connect broadcast behaviour to mixed behaviour

- Cargo.lock
- crates/sequencing/papyrus_consensus/Cargo.toml
- crates/sequencing/papyrus_consensus/src/lib.rs
- crates/sequencing/papyrus_consensus/src/types.rs
- crates/sequencing/papyrus_consensus/src/types_test.rs
Context defines how consensus will interact with the rest of the node.
ConsensusBlock defines the interface that Consensus needs for holding onto a proposal once it is
built.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1993)
> feat(consensus): define Context and ConsensusBlock traits

- crates/papyrus_network/src/converters/protobuf_conversion/transaction.rs
feat(network): add conversion from InvokeTransactionV3 to protobuf InvokeV3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2017)
> feat(network): add conversion from InvokeTransactionV3 to protobuf InvokeV3

- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/swarm_trait.rs
- crates/papyrus_network/src/network_manager/test.rs
- crates/papyrus_network/src/utils.rs
- feat(network): add register_broadcast_subscribers without connecting to behaviour
- feat(network): connect broadcast subscribers to behaviour
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/1986)
> feat(network): connect broadcast subscribers to behaviour

- crates/papyrus_rpc/src/v0_6/execution_test.rs
- crates/papyrus_rpc/src/v0_7/execution_test.rs
- crates/papyrus_storage/src/body/events.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/db/mod.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serialization/serializers.rs
- crates/papyrus_storage/src/test_instances.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2022)
> perf(storage)!: merge tabels with tx index key

- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/test.rs
- feat(network): add register_broadcast_subscribers without connecting to behaviour
- feat(network): connect broadcast subscribers to behaviour
- test(network): add tests for broadcast subscriber in network manager
- fix(network): report callback reports the originating peer
- feat(network): register_broadcast_subscriber receives any type with TryFrom/Into<Bytes>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> feat(network): register_broadcast_subscriber receives any type with TryFrom/Into<Bytes>

- crates/papyrus_protobuf/src/converters/header.rs
- crates/papyrus_protobuf/src/converters/header_test.rs
- crates/papyrus_protobuf/src/sync.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2063)
> feat(network): add wrapper for Option<SignedBlockHeader> and add converters to/from Vec<u8>

- crates/papyrus_protobuf/src/converters/receipt.rs
- crates/papyrus_protobuf/src/converters/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2055)
> feat(network): add conversion from protobuf transaction outputs to sn api

- Cargo.lock
- crates/sequencing/papyrus_consensus/Cargo.toml
- crates/sequencing/papyrus_consensus/src/lib.rs
- crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
- crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
- crates/sequencing/papyrus_consensus/src/test_utils.rs
- crates/sequencing/papyrus_consensus/src/types.rs
- crates/sequencing/papyrus_consensus/src/types_test.rs
This involved some updating to the ConsensusBlock trait, mostly to better explain the design.
We implemented just the milestone 1 proposal flow for SHC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2058)
> feat(consensus): create SingleHeightConsensus struct

- Cargo.lock
- crates/sequencing/papyrus_consensus/Cargo.toml
- crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
- crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
- crates/sequencing/papyrus_consensus/src/types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2064)
> feat(consensus): add an error type for consensus and utlize in SingleHeightConsensus

- crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
- crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
This is because SHC is dropped after each height, and async_channel allows cloning the Receiver.
So the manager can hold a Receiver and clone a new one to pass to SHC for each height.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2069)
> feat(consensus): change the channel type for Peering to SingleHeightConsensus messages

- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/test.rs
- crates/papyrus_node/src/main.rs
- crates/papyrus_p2p_sync/src/header_test.rs
- crates/papyrus_p2p_sync/src/lib.rs
- crates/papyrus_p2p_sync/src/state_diff_test.rs
- crates/papyrus_p2p_sync/src/test_utils.rs
- refactor(network): register_sqmr_subscriber receives one protocol and is generic on response type
- refactor(network): register_sqmr_subscriber is generic on query type
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2086)
> refactor(network): register_sqmr_subscriber is generic on query type

- crates/papyrus_storage/src/body/events.rs
- crates/papyrus_storage/src/body/events_test.rs
- crates/papyrus_storage/src/body/mod.rs
- crates/papyrus_storage/src/lib.rs
- crates/papyrus_storage/src/serialization/serializers.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2062)
> perf(storage)!: not save event_offset in the events table

- crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
- crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
- crates/sequencing/papyrus_consensus/src/test_utils.rs
- crates/sequencing/papyrus_consensus/src/types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2103)
> refactor(consensus): move network sender to the context

- crates/papyrus_network/src/bin/streamed_bytes_benchmark.rs
- crates/papyrus_network/src/db_executor/mod.rs
- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/swarm_trait.rs
- crates/papyrus_network/src/network_manager/test.rs
- crates/papyrus_network/src/sqmr/behaviour.rs
- crates/papyrus_network/src/sqmr/behaviour_test.rs
- crates/papyrus_network/src/sqmr/flow_test.rs
- crates/papyrus_network/src/sqmr/handler/inbound_session.rs
- crates/papyrus_network/src/sqmr/handler_test.rs
- crates/papyrus_network/src/sqmr/messages.rs
- crates/papyrus_network/src/sqmr/messages_test.rs
- crates/papyrus_network/src/sqmr/mod.rs
- crates/papyrus_network/src/sqmr/protocol_test.rs
- feat(network): remove stream in DBExecutorTrait
- refactor(network): remove QueryId from db executor
- revert(network): revert sending length prefixed data (with conflicts)
- revert(network): resolve conflicts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2096)
> revert(network): revert sending length prefixed data

- crates/papyrus_network/src/db_executor/mod.rs
- crates/papyrus_network/src/lib.rs
- crates/test_utils/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2110)
> chore: update clippy errors for 06.16.2024

- Cargo.lock
- crates/sequencing/papyrus_consensus/Cargo.toml
- crates/sequencing/papyrus_consensus/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2108)
> feat(consensus): add run_consensus

- Cargo.lock
- crates/papyrus_common/src/state.rs
- crates/papyrus_protobuf/Cargo.toml
- crates/papyrus_protobuf/src/converters/state_diff.rs
- crates/papyrus_protobuf/src/sync.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2115)
> test(protobuf): add auto impl for statediffchunk

- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2114)
> fix(network): dont check fin in network manager

- crates/papyrus_network/src/db_executor/mod.rs
- crates/papyrus_network/src/db_executor/test.rs
- crates/papyrus_network/src/network_manager/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2113)
> refactor(network): use DataOrFin in db executor's Data

- crates/papyrus_network/src/network_manager/test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2109)
> refactor(network): remove protobuf from network_manager test

- crates/papyrus_network/src/network_manager/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2127)
> test(network): add register_broadcast_subscriber for test

- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/test.rs
- refactor(network): remove Data from db executor
- refactor(network): db executor communicates through channels
- refactor(network): db executor is removed from NetworkManager and runs in a separate task
- WIP
- test(network): return network manager tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2124)
> test(network): return network manager tests

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/db_executor/mod.rs
- crates/papyrus_network/src/db_executor/test.rs
- crates/papyrus_network/src/lib.rs
- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/test.rs
- crates/papyrus_node/src/main.rs
- refactor(network): remove Data from db executor
- refactor(network): db executor communicates through channels
- refactor(network): db executor is removed from NetworkManager and runs in a separate task
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2122)
> refactor(network): db executor is removed from NetworkManager and runs in a separate task

- Cargo.lock
- crates/papyrus_network/Cargo.toml
- crates/papyrus_network/src/db_executor/mod.rs
- crates/papyrus_network/src/db_executor/test.rs
- crates/papyrus_network/src/lib.rs
- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/test.rs
- crates/papyrus_node/src/main.rs
- refactor(network): remove Data from db executor
- refactor(network): db executor communicates through channels
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2121)
> refactor(network): db executor communicates through channels

- crates/papyrus_network/src/db_executor/mod.rs
- crates/papyrus_network/src/db_executor/test.rs
- crates/papyrus_network/src/lib.rs
- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_node/src/main.rs
- crates/papyrus_protobuf/src/converters/transaction.rs
- crates/papyrus_protobuf/src/sync.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2135)
> feat(network): add Transaction Protocol

- crates/papyrus_node/src/main.rs
- crates/sequencing/papyrus_consensus/src/lib.rs
- crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2138)
> feat(consensus): add tracing instrumentation and logging to consensus

- .github/workflows/ci.yml
- crates/sequencing/papyrus_block_builder/src/lib.rs
- crates/sequencing/papyrus_consensus/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2134)
> feat(consensus): add sequencing crates to some CI flows

- crates/papyrus_rpc/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2164)
> chore: externalize compiled contract class for mempool

- Cargo.lock
- crates/papyrus_p2p_sync/Cargo.toml
- crates/papyrus_p2p_sync/src/client/mod.rs
- crates/papyrus_p2p_sync/src/client/state_diff.rs
- crates/papyrus_p2p_sync/src/client/state_diff_test.rs
- crates/papyrus_p2p_sync/src/client/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2118)
> chore(sync): receive statediffchunk from network

- Cargo.lock
- Cargo.toml
- crates/papyrus_protobuf/src/converters/header.rs
- crates/papyrus_storage/src/header.rs
- crates/papyrus_storage/src/serialization/serializers.rs
- crates/papyrus_storage/src/test_instances.rs
- crates/papyrus_sync/src/sources/central.rs
- crates/starknet_client/src/reader/objects/block.rs
- crates/starknet_client/src/reader/objects/block_test.rs
- crates/test_utils/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2180)
> fix: put none in commitments if they come from a deprecated formula

- crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
- crates/sequencing/papyrus_consensus/src/test_utils.rs
- crates/sequencing/papyrus_consensus/src/types.rs
This is separate from  since propose should eventually be streamed on the network.
Therefore we mock that via a specialized fn in Context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2169)
> feat(consensus): add broadcast method to Context trait for any ConsensusMessage

- crates/papyrus_protobuf/src/consensus.rs
- crates/sequencing/papyrus_consensus/src/lib.rs
- crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
Currently the context is hard coded with 4 validators, so at least 3 must vote in favor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2189)
> feat(consensus): update consensus so that it runs with voting

- crates/papyrus_network/src/network_manager/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2208)
> fix(network): replace panic with error in unexpected swarm event

- crates/papyrus_network/src/e2e_broadcast_test.rs
- crates/papyrus_network/src/lib.rs
- feat(network): add register_broadcast_subscribers without connecting to behaviour
- feat(network): connect broadcast subscribers to behaviour
- test(network): add tests for broadcast subscriber in network manager
- fix(network): report callback reports the originating peer
- feat(network): register_broadcast_subscriber receives any type with TryFrom/Into<Bytes>
- fix(network): replace unimplemented broadcast behaviour with gossipsub
- test(network): add …
> test(network): add broadcast e2e test

- crates/papyrus_node/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2223)
> feat(consensus): consensus network buffer size uses the default value

- crates/papyrus_network/src/network_manager/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2230)
> chore(network): conversion from SyncClientQueryForNetwork to SyncClient

- crates/sequencing/papyrus_consensus/src/state_machine.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2231)
> chore(consensus): fix typo in state machine

- crates/papyrus_network/src/lib.rs
- crates/papyrus_network/src/network_manager/mod.rs
- crates/papyrus_network/src/network_manager/test.rs
- crates/papyrus_node/src/main.rs
- crates/papyrus_p2p_sync/src/client/header_test.rs
- crates/papyrus_p2p_sync/src/client/mod.rs
- crates/papyrus_p2p_sync/src/client/state_diff_test.rs
- crates/papyrus_p2p_sync/src/client/stream_builder.rs
- crates/papyrus_p2p_sync/src/client/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2233)
> refactor(network): move responses sender into query sender

- crates/sequencing/papyrus_consensus/run_consensus.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2227)
> chore(consensus): allow running multiple simulations of consensus

- crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
This is now possible since we no longer put the Context in an Arc, which forced us to
set expectations before doing that. Setting expectations requires .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2239)
> refactor(consensus): put expectations near the most relevant call site for SHC tests

- crates/sequencing/papyrus_consensus/src/lib.rs
- crates/sequencing/papyrus_consensus/src/papyrus_consensus_context.rs
- crates/sequencing/papyrus_consensus/src/single_height_consensus.rs
- crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs
- crates/sequencing/papyrus_consensus/src/test_utils.rs
- crates/sequencing/papyrus_consensus/src/types.rs
This allows us to remove the Arc<Mutex> and also avoid cloning the sender on every call.
The cost is that we leak the fact that futures Sender requires .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/papyrus/2241)
> refactor(consensus): change the broadcast fn in context to take 'ref mut self'
